// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: proto/news/news.proto

//服务名

package news

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

import (
	context "context"
	api "github.com/micro/go-micro/v2/api"
	client "github.com/micro/go-micro/v2/client"
	server "github.com/micro/go-micro/v2/server"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Reference imports to suppress errors if they are not otherwise used.
var _ api.Endpoint
var _ context.Context
var _ client.Option
var _ server.Option

// Api Endpoints for NewsService service

func NewNewsServiceEndpoints() []*api.Endpoint {
	return []*api.Endpoint{}
}

// Client API for NewsService service

type NewsService interface {
	GetMessageByUserID(ctx context.Context, in *GetMessageByUserIDParam, opts ...client.CallOption) (*GetMessageByUserIDResponse, error)
	GetMessageByCourseID(ctx context.Context, in *GetMessageByCourseIDParam, opts ...client.CallOption) (*GetMessageByCourseIDResponse, error)
}

type newsService struct {
	c    client.Client
	name string
}

func NewNewsService(name string, c client.Client) NewsService {
	return &newsService{
		c:    c,
		name: name,
	}
}

func (c *newsService) GetMessageByUserID(ctx context.Context, in *GetMessageByUserIDParam, opts ...client.CallOption) (*GetMessageByUserIDResponse, error) {
	req := c.c.NewRequest(c.name, "NewsService.GetMessageByUserID", in)
	out := new(GetMessageByUserIDResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *newsService) GetMessageByCourseID(ctx context.Context, in *GetMessageByCourseIDParam, opts ...client.CallOption) (*GetMessageByCourseIDResponse, error) {
	req := c.c.NewRequest(c.name, "NewsService.GetMessageByCourseID", in)
	out := new(GetMessageByCourseIDResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for NewsService service

type NewsServiceHandler interface {
	GetMessageByUserID(context.Context, *GetMessageByUserIDParam, *GetMessageByUserIDResponse) error
	GetMessageByCourseID(context.Context, *GetMessageByCourseIDParam, *GetMessageByCourseIDResponse) error
}

func RegisterNewsServiceHandler(s server.Server, hdlr NewsServiceHandler, opts ...server.HandlerOption) error {
	type newsService interface {
		GetMessageByUserID(ctx context.Context, in *GetMessageByUserIDParam, out *GetMessageByUserIDResponse) error
		GetMessageByCourseID(ctx context.Context, in *GetMessageByCourseIDParam, out *GetMessageByCourseIDResponse) error
	}
	type NewsService struct {
		newsService
	}
	h := &newsServiceHandler{hdlr}
	return s.Handle(s.NewHandler(&NewsService{h}, opts...))
}

type newsServiceHandler struct {
	NewsServiceHandler
}

func (h *newsServiceHandler) GetMessageByUserID(ctx context.Context, in *GetMessageByUserIDParam, out *GetMessageByUserIDResponse) error {
	return h.NewsServiceHandler.GetMessageByUserID(ctx, in, out)
}

func (h *newsServiceHandler) GetMessageByCourseID(ctx context.Context, in *GetMessageByCourseIDParam, out *GetMessageByCourseIDResponse) error {
	return h.NewsServiceHandler.GetMessageByCourseID(ctx, in, out)
}
