// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: proto/user/user.proto

//服务名

package user

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

import (
	context "context"
	api "github.com/micro/go-micro/v2/api"
	client "github.com/micro/go-micro/v2/client"
	server "github.com/micro/go-micro/v2/server"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Reference imports to suppress errors if they are not otherwise used.
var _ api.Endpoint
var _ context.Context
var _ client.Option
var _ server.Option

// Api Endpoints for UserService service

func NewUserServiceEndpoints() []*api.Endpoint {
	return []*api.Endpoint{}
}

// Client API for UserService service

type UserService interface {
	AddUser(ctx context.Context, in *User, opts ...client.CallOption) (*EditResponse, error)
	DeleteUser(ctx context.Context, in *UserID, opts ...client.CallOption) (*EditResponse, error)
	UpdateUser(ctx context.Context, in *User, opts ...client.CallOption) (*EditResponse, error)
	SearchUser(ctx context.Context, in *UserID, opts ...client.CallOption) (*SearchResponse, error)
	SearchUsers(ctx context.Context, in *UserIDArray, opts ...client.CallOption) (*SearchUsersResponse, error)
}

type userService struct {
	c    client.Client
	name string
}

func NewUserService(name string, c client.Client) UserService {
	return &userService{
		c:    c,
		name: name,
	}
}

func (c *userService) AddUser(ctx context.Context, in *User, opts ...client.CallOption) (*EditResponse, error) {
	req := c.c.NewRequest(c.name, "UserService.AddUser", in)
	out := new(EditResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userService) DeleteUser(ctx context.Context, in *UserID, opts ...client.CallOption) (*EditResponse, error) {
	req := c.c.NewRequest(c.name, "UserService.DeleteUser", in)
	out := new(EditResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userService) UpdateUser(ctx context.Context, in *User, opts ...client.CallOption) (*EditResponse, error) {
	req := c.c.NewRequest(c.name, "UserService.UpdateUser", in)
	out := new(EditResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userService) SearchUser(ctx context.Context, in *UserID, opts ...client.CallOption) (*SearchResponse, error) {
	req := c.c.NewRequest(c.name, "UserService.SearchUser", in)
	out := new(SearchResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userService) SearchUsers(ctx context.Context, in *UserIDArray, opts ...client.CallOption) (*SearchUsersResponse, error) {
	req := c.c.NewRequest(c.name, "UserService.SearchUsers", in)
	out := new(SearchUsersResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for UserService service

type UserServiceHandler interface {
	AddUser(context.Context, *User, *EditResponse) error
	DeleteUser(context.Context, *UserID, *EditResponse) error
	UpdateUser(context.Context, *User, *EditResponse) error
	SearchUser(context.Context, *UserID, *SearchResponse) error
	SearchUsers(context.Context, *UserIDArray, *SearchUsersResponse) error
}

func RegisterUserServiceHandler(s server.Server, hdlr UserServiceHandler, opts ...server.HandlerOption) error {
	type userService interface {
		AddUser(ctx context.Context, in *User, out *EditResponse) error
		DeleteUser(ctx context.Context, in *UserID, out *EditResponse) error
		UpdateUser(ctx context.Context, in *User, out *EditResponse) error
		SearchUser(ctx context.Context, in *UserID, out *SearchResponse) error
		SearchUsers(ctx context.Context, in *UserIDArray, out *SearchUsersResponse) error
	}
	type UserService struct {
		userService
	}
	h := &userServiceHandler{hdlr}
	return s.Handle(s.NewHandler(&UserService{h}, opts...))
}

type userServiceHandler struct {
	UserServiceHandler
}

func (h *userServiceHandler) AddUser(ctx context.Context, in *User, out *EditResponse) error {
	return h.UserServiceHandler.AddUser(ctx, in, out)
}

func (h *userServiceHandler) DeleteUser(ctx context.Context, in *UserID, out *EditResponse) error {
	return h.UserServiceHandler.DeleteUser(ctx, in, out)
}

func (h *userServiceHandler) UpdateUser(ctx context.Context, in *User, out *EditResponse) error {
	return h.UserServiceHandler.UpdateUser(ctx, in, out)
}

func (h *userServiceHandler) SearchUser(ctx context.Context, in *UserID, out *SearchResponse) error {
	return h.UserServiceHandler.SearchUser(ctx, in, out)
}

func (h *userServiceHandler) SearchUsers(ctx context.Context, in *UserIDArray, out *SearchUsersResponse) error {
	return h.UserServiceHandler.SearchUsers(ctx, in, out)
}
