//声明proto本版

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0
// 	protoc        v3.14.0
// source: proto/answer/answer.proto

//服务名

package answer

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type CreateAnswerResponse_Status int32

const (
	CreateAnswerResponse_SUCCESS CreateAnswerResponse_Status = 0
	CreateAnswerResponse_ERROR   CreateAnswerResponse_Status = -1
)

// Enum value maps for CreateAnswerResponse_Status.
var (
	CreateAnswerResponse_Status_name = map[int32]string{
		0:  "SUCCESS",
		-1: "ERROR",
	}
	CreateAnswerResponse_Status_value = map[string]int32{
		"SUCCESS": 0,
		"ERROR":   -1,
	}
)

func (x CreateAnswerResponse_Status) Enum() *CreateAnswerResponse_Status {
	p := new(CreateAnswerResponse_Status)
	*p = x
	return p
}

func (x CreateAnswerResponse_Status) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (CreateAnswerResponse_Status) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_answer_answer_proto_enumTypes[0].Descriptor()
}

func (CreateAnswerResponse_Status) Type() protoreflect.EnumType {
	return &file_proto_answer_answer_proto_enumTypes[0]
}

func (x CreateAnswerResponse_Status) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use CreateAnswerResponse_Status.Descriptor instead.
func (CreateAnswerResponse_Status) EnumDescriptor() ([]byte, []int) {
	return file_proto_answer_answer_proto_rawDescGZIP(), []int{6, 0}
}

type DeleteAnswerResponse_Status int32

const (
	DeleteAnswerResponse_SUCCESS DeleteAnswerResponse_Status = 0
	DeleteAnswerResponse_ERROR   DeleteAnswerResponse_Status = -1
)

// Enum value maps for DeleteAnswerResponse_Status.
var (
	DeleteAnswerResponse_Status_name = map[int32]string{
		0:  "SUCCESS",
		-1: "ERROR",
	}
	DeleteAnswerResponse_Status_value = map[string]int32{
		"SUCCESS": 0,
		"ERROR":   -1,
	}
)

func (x DeleteAnswerResponse_Status) Enum() *DeleteAnswerResponse_Status {
	p := new(DeleteAnswerResponse_Status)
	*p = x
	return p
}

func (x DeleteAnswerResponse_Status) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (DeleteAnswerResponse_Status) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_answer_answer_proto_enumTypes[1].Descriptor()
}

func (DeleteAnswerResponse_Status) Type() protoreflect.EnumType {
	return &file_proto_answer_answer_proto_enumTypes[1]
}

func (x DeleteAnswerResponse_Status) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use DeleteAnswerResponse_Status.Descriptor instead.
func (DeleteAnswerResponse_Status) EnumDescriptor() ([]byte, []int) {
	return file_proto_answer_answer_proto_rawDescGZIP(), []int{7, 0}
}

type UpdateAnswerResponse_Status int32

const (
	UpdateAnswerResponse_SUCCESS UpdateAnswerResponse_Status = 0
	UpdateAnswerResponse_ERROR   UpdateAnswerResponse_Status = -1
)

// Enum value maps for UpdateAnswerResponse_Status.
var (
	UpdateAnswerResponse_Status_name = map[int32]string{
		0:  "SUCCESS",
		-1: "ERROR",
	}
	UpdateAnswerResponse_Status_value = map[string]int32{
		"SUCCESS": 0,
		"ERROR":   -1,
	}
)

func (x UpdateAnswerResponse_Status) Enum() *UpdateAnswerResponse_Status {
	p := new(UpdateAnswerResponse_Status)
	*p = x
	return p
}

func (x UpdateAnswerResponse_Status) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (UpdateAnswerResponse_Status) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_answer_answer_proto_enumTypes[2].Descriptor()
}

func (UpdateAnswerResponse_Status) Type() protoreflect.EnumType {
	return &file_proto_answer_answer_proto_enumTypes[2]
}

func (x UpdateAnswerResponse_Status) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use UpdateAnswerResponse_Status.Descriptor instead.
func (UpdateAnswerResponse_Status) EnumDescriptor() ([]byte, []int) {
	return file_proto_answer_answer_proto_rawDescGZIP(), []int{8, 0}
}

type SearchAnswerResponse_Status int32

const (
	SearchAnswerResponse_SUCCESS SearchAnswerResponse_Status = 0
	SearchAnswerResponse_ERROR   SearchAnswerResponse_Status = -1
)

// Enum value maps for SearchAnswerResponse_Status.
var (
	SearchAnswerResponse_Status_name = map[int32]string{
		0:  "SUCCESS",
		-1: "ERROR",
	}
	SearchAnswerResponse_Status_value = map[string]int32{
		"SUCCESS": 0,
		"ERROR":   -1,
	}
)

func (x SearchAnswerResponse_Status) Enum() *SearchAnswerResponse_Status {
	p := new(SearchAnswerResponse_Status)
	*p = x
	return p
}

func (x SearchAnswerResponse_Status) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SearchAnswerResponse_Status) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_answer_answer_proto_enumTypes[3].Descriptor()
}

func (SearchAnswerResponse_Status) Type() protoreflect.EnumType {
	return &file_proto_answer_answer_proto_enumTypes[3]
}

func (x SearchAnswerResponse_Status) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SearchAnswerResponse_Status.Descriptor instead.
func (SearchAnswerResponse_Status) EnumDescriptor() ([]byte, []int) {
	return file_proto_answer_answer_proto_rawDescGZIP(), []int{9, 0}
}

type SearchAnswerByStudentIDResponse_Status int32

const (
	SearchAnswerByStudentIDResponse_SUCCESS SearchAnswerByStudentIDResponse_Status = 0
	SearchAnswerByStudentIDResponse_ERROR   SearchAnswerByStudentIDResponse_Status = -1
)

// Enum value maps for SearchAnswerByStudentIDResponse_Status.
var (
	SearchAnswerByStudentIDResponse_Status_name = map[int32]string{
		0:  "SUCCESS",
		-1: "ERROR",
	}
	SearchAnswerByStudentIDResponse_Status_value = map[string]int32{
		"SUCCESS": 0,
		"ERROR":   -1,
	}
)

func (x SearchAnswerByStudentIDResponse_Status) Enum() *SearchAnswerByStudentIDResponse_Status {
	p := new(SearchAnswerByStudentIDResponse_Status)
	*p = x
	return p
}

func (x SearchAnswerByStudentIDResponse_Status) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SearchAnswerByStudentIDResponse_Status) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_answer_answer_proto_enumTypes[4].Descriptor()
}

func (SearchAnswerByStudentIDResponse_Status) Type() protoreflect.EnumType {
	return &file_proto_answer_answer_proto_enumTypes[4]
}

func (x SearchAnswerByStudentIDResponse_Status) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SearchAnswerByStudentIDResponse_Status.Descriptor instead.
func (SearchAnswerByStudentIDResponse_Status) EnumDescriptor() ([]byte, []int) {
	return file_proto_answer_answer_proto_rawDescGZIP(), []int{10, 0}
}

type SearchAnswerByHomeworkIDResponse_Status int32

const (
	SearchAnswerByHomeworkIDResponse_SUCCESS SearchAnswerByHomeworkIDResponse_Status = 0
	SearchAnswerByHomeworkIDResponse_ERROR   SearchAnswerByHomeworkIDResponse_Status = -1
)

// Enum value maps for SearchAnswerByHomeworkIDResponse_Status.
var (
	SearchAnswerByHomeworkIDResponse_Status_name = map[int32]string{
		0:  "SUCCESS",
		-1: "ERROR",
	}
	SearchAnswerByHomeworkIDResponse_Status_value = map[string]int32{
		"SUCCESS": 0,
		"ERROR":   -1,
	}
)

func (x SearchAnswerByHomeworkIDResponse_Status) Enum() *SearchAnswerByHomeworkIDResponse_Status {
	p := new(SearchAnswerByHomeworkIDResponse_Status)
	*p = x
	return p
}

func (x SearchAnswerByHomeworkIDResponse_Status) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SearchAnswerByHomeworkIDResponse_Status) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_answer_answer_proto_enumTypes[5].Descriptor()
}

func (SearchAnswerByHomeworkIDResponse_Status) Type() protoreflect.EnumType {
	return &file_proto_answer_answer_proto_enumTypes[5]
}

func (x SearchAnswerByHomeworkIDResponse_Status) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SearchAnswerByHomeworkIDResponse_Status.Descriptor instead.
func (SearchAnswerByHomeworkIDResponse_Status) EnumDescriptor() ([]byte, []int) {
	return file_proto_answer_answer_proto_rawDescGZIP(), []int{11, 0}
}

type SearchAnswerByStudentIDAndHomeworkIDResponse_Status int32

const (
	SearchAnswerByStudentIDAndHomeworkIDResponse_SUCCESS SearchAnswerByStudentIDAndHomeworkIDResponse_Status = 0
	SearchAnswerByStudentIDAndHomeworkIDResponse_ERROR   SearchAnswerByStudentIDAndHomeworkIDResponse_Status = 1
)

// Enum value maps for SearchAnswerByStudentIDAndHomeworkIDResponse_Status.
var (
	SearchAnswerByStudentIDAndHomeworkIDResponse_Status_name = map[int32]string{
		0: "SUCCESS",
		1: "ERROR",
	}
	SearchAnswerByStudentIDAndHomeworkIDResponse_Status_value = map[string]int32{
		"SUCCESS": 0,
		"ERROR":   1,
	}
)

func (x SearchAnswerByStudentIDAndHomeworkIDResponse_Status) Enum() *SearchAnswerByStudentIDAndHomeworkIDResponse_Status {
	p := new(SearchAnswerByStudentIDAndHomeworkIDResponse_Status)
	*p = x
	return p
}

func (x SearchAnswerByStudentIDAndHomeworkIDResponse_Status) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SearchAnswerByStudentIDAndHomeworkIDResponse_Status) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_answer_answer_proto_enumTypes[6].Descriptor()
}

func (SearchAnswerByStudentIDAndHomeworkIDResponse_Status) Type() protoreflect.EnumType {
	return &file_proto_answer_answer_proto_enumTypes[6]
}

func (x SearchAnswerByStudentIDAndHomeworkIDResponse_Status) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SearchAnswerByStudentIDAndHomeworkIDResponse_Status.Descriptor instead.
func (SearchAnswerByStudentIDAndHomeworkIDResponse_Status) EnumDescriptor() ([]byte, []int) {
	return file_proto_answer_answer_proto_rawDescGZIP(), []int{12, 0}
}

//Parameter protocol
type CreateAnswerParam struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	HomeworkID int32  `protobuf:"varint,1,opt,name=homeworkID,proto3" json:"homeworkID,omitempty"`
	StudentID  int32  `protobuf:"varint,2,opt,name=studentID,proto3" json:"studentID,omitempty"`
	Status     int32  `protobuf:"varint,3,opt,name=status,proto3" json:"status,omitempty"`
	CommitTime int64  `protobuf:"varint,4,opt,name=commit_time,json=commitTime,proto3" json:"commit_time,omitempty"`
	AnswerJson string `protobuf:"bytes,5,opt,name=answer_json,json=answerJson,proto3" json:"answer_json,omitempty"`
}

func (x *CreateAnswerParam) Reset() {
	*x = CreateAnswerParam{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_answer_answer_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateAnswerParam) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateAnswerParam) ProtoMessage() {}

func (x *CreateAnswerParam) ProtoReflect() protoreflect.Message {
	mi := &file_proto_answer_answer_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateAnswerParam.ProtoReflect.Descriptor instead.
func (*CreateAnswerParam) Descriptor() ([]byte, []int) {
	return file_proto_answer_answer_proto_rawDescGZIP(), []int{0}
}

func (x *CreateAnswerParam) GetHomeworkID() int32 {
	if x != nil {
		return x.HomeworkID
	}
	return 0
}

func (x *CreateAnswerParam) GetStudentID() int32 {
	if x != nil {
		return x.StudentID
	}
	return 0
}

func (x *CreateAnswerParam) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *CreateAnswerParam) GetCommitTime() int64 {
	if x != nil {
		return x.CommitTime
	}
	return 0
}

func (x *CreateAnswerParam) GetAnswerJson() string {
	if x != nil {
		return x.AnswerJson
	}
	return ""
}

type AnswerID struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AnswerID int32 `protobuf:"varint,1,opt,name=AnswerID,proto3" json:"AnswerID,omitempty"`
}

func (x *AnswerID) Reset() {
	*x = AnswerID{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_answer_answer_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AnswerID) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AnswerID) ProtoMessage() {}

func (x *AnswerID) ProtoReflect() protoreflect.Message {
	mi := &file_proto_answer_answer_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AnswerID.ProtoReflect.Descriptor instead.
func (*AnswerID) Descriptor() ([]byte, []int) {
	return file_proto_answer_answer_proto_rawDescGZIP(), []int{1}
}

func (x *AnswerID) GetAnswerID() int32 {
	if x != nil {
		return x.AnswerID
	}
	return 0
}

type AnswerInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AnswerID   int32  `protobuf:"varint,1,opt,name=AnswerID,proto3" json:"AnswerID,omitempty"`
	HomeworkID int32  `protobuf:"varint,2,opt,name=homeworkID,proto3" json:"homeworkID,omitempty"`
	StudentID  int32  `protobuf:"varint,3,opt,name=studentID,proto3" json:"studentID,omitempty"`
	Status     int32  `protobuf:"varint,4,opt,name=status,proto3" json:"status,omitempty"`
	CommitTime int64  `protobuf:"varint,5,opt,name=commit_time,json=commitTime,proto3" json:"commit_time,omitempty"`
	AnswerJson string `protobuf:"bytes,6,opt,name=answer_json,json=answerJson,proto3" json:"answer_json,omitempty"`
}

func (x *AnswerInfo) Reset() {
	*x = AnswerInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_answer_answer_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AnswerInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AnswerInfo) ProtoMessage() {}

func (x *AnswerInfo) ProtoReflect() protoreflect.Message {
	mi := &file_proto_answer_answer_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AnswerInfo.ProtoReflect.Descriptor instead.
func (*AnswerInfo) Descriptor() ([]byte, []int) {
	return file_proto_answer_answer_proto_rawDescGZIP(), []int{2}
}

func (x *AnswerInfo) GetAnswerID() int32 {
	if x != nil {
		return x.AnswerID
	}
	return 0
}

func (x *AnswerInfo) GetHomeworkID() int32 {
	if x != nil {
		return x.HomeworkID
	}
	return 0
}

func (x *AnswerInfo) GetStudentID() int32 {
	if x != nil {
		return x.StudentID
	}
	return 0
}

func (x *AnswerInfo) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *AnswerInfo) GetCommitTime() int64 {
	if x != nil {
		return x.CommitTime
	}
	return 0
}

func (x *AnswerInfo) GetAnswerJson() string {
	if x != nil {
		return x.AnswerJson
	}
	return ""
}

type StudentID struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	StudentID int32 `protobuf:"varint,1,opt,name=StudentID,proto3" json:"StudentID,omitempty"`
}

func (x *StudentID) Reset() {
	*x = StudentID{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_answer_answer_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StudentID) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StudentID) ProtoMessage() {}

func (x *StudentID) ProtoReflect() protoreflect.Message {
	mi := &file_proto_answer_answer_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StudentID.ProtoReflect.Descriptor instead.
func (*StudentID) Descriptor() ([]byte, []int) {
	return file_proto_answer_answer_proto_rawDescGZIP(), []int{3}
}

func (x *StudentID) GetStudentID() int32 {
	if x != nil {
		return x.StudentID
	}
	return 0
}

type HomeworkID struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	HomeworkID int32 `protobuf:"varint,1,opt,name=HomeworkID,proto3" json:"HomeworkID,omitempty"`
}

func (x *HomeworkID) Reset() {
	*x = HomeworkID{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_answer_answer_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HomeworkID) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HomeworkID) ProtoMessage() {}

func (x *HomeworkID) ProtoReflect() protoreflect.Message {
	mi := &file_proto_answer_answer_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HomeworkID.ProtoReflect.Descriptor instead.
func (*HomeworkID) Descriptor() ([]byte, []int) {
	return file_proto_answer_answer_proto_rawDescGZIP(), []int{4}
}

func (x *HomeworkID) GetHomeworkID() int32 {
	if x != nil {
		return x.HomeworkID
	}
	return 0
}

type StudentIDAndHomeworkID struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	StudentID  int32 `protobuf:"varint,1,opt,name=StudentID,proto3" json:"StudentID,omitempty"`
	HomeworkID int32 `protobuf:"varint,2,opt,name=HomeworkID,proto3" json:"HomeworkID,omitempty"`
}

func (x *StudentIDAndHomeworkID) Reset() {
	*x = StudentIDAndHomeworkID{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_answer_answer_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StudentIDAndHomeworkID) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StudentIDAndHomeworkID) ProtoMessage() {}

func (x *StudentIDAndHomeworkID) ProtoReflect() protoreflect.Message {
	mi := &file_proto_answer_answer_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StudentIDAndHomeworkID.ProtoReflect.Descriptor instead.
func (*StudentIDAndHomeworkID) Descriptor() ([]byte, []int) {
	return file_proto_answer_answer_proto_rawDescGZIP(), []int{5}
}

func (x *StudentIDAndHomeworkID) GetStudentID() int32 {
	if x != nil {
		return x.StudentID
	}
	return 0
}

func (x *StudentIDAndHomeworkID) GetHomeworkID() int32 {
	if x != nil {
		return x.HomeworkID
	}
	return 0
}

type CreateAnswerResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status   CreateAnswerResponse_Status `protobuf:"varint,1,opt,name=status,proto3,enum=go.micro.service.answer.CreateAnswerResponse_Status" json:"status,omitempty"`
	Msg      string                      `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	AnswerID int32                       `protobuf:"varint,3,opt,name=AnswerID,proto3" json:"AnswerID,omitempty"`
}

func (x *CreateAnswerResponse) Reset() {
	*x = CreateAnswerResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_answer_answer_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateAnswerResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateAnswerResponse) ProtoMessage() {}

func (x *CreateAnswerResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_answer_answer_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateAnswerResponse.ProtoReflect.Descriptor instead.
func (*CreateAnswerResponse) Descriptor() ([]byte, []int) {
	return file_proto_answer_answer_proto_rawDescGZIP(), []int{6}
}

func (x *CreateAnswerResponse) GetStatus() CreateAnswerResponse_Status {
	if x != nil {
		return x.Status
	}
	return CreateAnswerResponse_SUCCESS
}

func (x *CreateAnswerResponse) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

func (x *CreateAnswerResponse) GetAnswerID() int32 {
	if x != nil {
		return x.AnswerID
	}
	return 0
}

type DeleteAnswerResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status DeleteAnswerResponse_Status `protobuf:"varint,1,opt,name=status,proto3,enum=go.micro.service.answer.DeleteAnswerResponse_Status" json:"status,omitempty"`
	Msg    string                      `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
}

func (x *DeleteAnswerResponse) Reset() {
	*x = DeleteAnswerResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_answer_answer_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteAnswerResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteAnswerResponse) ProtoMessage() {}

func (x *DeleteAnswerResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_answer_answer_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteAnswerResponse.ProtoReflect.Descriptor instead.
func (*DeleteAnswerResponse) Descriptor() ([]byte, []int) {
	return file_proto_answer_answer_proto_rawDescGZIP(), []int{7}
}

func (x *DeleteAnswerResponse) GetStatus() DeleteAnswerResponse_Status {
	if x != nil {
		return x.Status
	}
	return DeleteAnswerResponse_SUCCESS
}

func (x *DeleteAnswerResponse) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

type UpdateAnswerResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status UpdateAnswerResponse_Status `protobuf:"varint,1,opt,name=status,proto3,enum=go.micro.service.answer.UpdateAnswerResponse_Status" json:"status,omitempty"`
	Msg    string                      `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
}

func (x *UpdateAnswerResponse) Reset() {
	*x = UpdateAnswerResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_answer_answer_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateAnswerResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateAnswerResponse) ProtoMessage() {}

func (x *UpdateAnswerResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_answer_answer_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateAnswerResponse.ProtoReflect.Descriptor instead.
func (*UpdateAnswerResponse) Descriptor() ([]byte, []int) {
	return file_proto_answer_answer_proto_rawDescGZIP(), []int{8}
}

func (x *UpdateAnswerResponse) GetStatus() UpdateAnswerResponse_Status {
	if x != nil {
		return x.Status
	}
	return UpdateAnswerResponse_SUCCESS
}

func (x *UpdateAnswerResponse) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

type SearchAnswerResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status SearchAnswerResponse_Status `protobuf:"varint,1,opt,name=status,proto3,enum=go.micro.service.answer.SearchAnswerResponse_Status" json:"status,omitempty"`
	Msg    string                      `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	Answer *AnswerInfo                 `protobuf:"bytes,3,opt,name=answer,proto3" json:"answer,omitempty"`
}

func (x *SearchAnswerResponse) Reset() {
	*x = SearchAnswerResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_answer_answer_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SearchAnswerResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchAnswerResponse) ProtoMessage() {}

func (x *SearchAnswerResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_answer_answer_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchAnswerResponse.ProtoReflect.Descriptor instead.
func (*SearchAnswerResponse) Descriptor() ([]byte, []int) {
	return file_proto_answer_answer_proto_rawDescGZIP(), []int{9}
}

func (x *SearchAnswerResponse) GetStatus() SearchAnswerResponse_Status {
	if x != nil {
		return x.Status
	}
	return SearchAnswerResponse_SUCCESS
}

func (x *SearchAnswerResponse) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

func (x *SearchAnswerResponse) GetAnswer() *AnswerInfo {
	if x != nil {
		return x.Answer
	}
	return nil
}

type SearchAnswerByStudentIDResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status  SearchAnswerByStudentIDResponse_Status `protobuf:"varint,1,opt,name=status,proto3,enum=go.micro.service.answer.SearchAnswerByStudentIDResponse_Status" json:"status,omitempty"`
	Msg     string                                 `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	Answers []*AnswerInfo                          `protobuf:"bytes,3,rep,name=answers,proto3" json:"answers,omitempty"`
}

func (x *SearchAnswerByStudentIDResponse) Reset() {
	*x = SearchAnswerByStudentIDResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_answer_answer_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SearchAnswerByStudentIDResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchAnswerByStudentIDResponse) ProtoMessage() {}

func (x *SearchAnswerByStudentIDResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_answer_answer_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchAnswerByStudentIDResponse.ProtoReflect.Descriptor instead.
func (*SearchAnswerByStudentIDResponse) Descriptor() ([]byte, []int) {
	return file_proto_answer_answer_proto_rawDescGZIP(), []int{10}
}

func (x *SearchAnswerByStudentIDResponse) GetStatus() SearchAnswerByStudentIDResponse_Status {
	if x != nil {
		return x.Status
	}
	return SearchAnswerByStudentIDResponse_SUCCESS
}

func (x *SearchAnswerByStudentIDResponse) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

func (x *SearchAnswerByStudentIDResponse) GetAnswers() []*AnswerInfo {
	if x != nil {
		return x.Answers
	}
	return nil
}

type SearchAnswerByHomeworkIDResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status  SearchAnswerByHomeworkIDResponse_Status `protobuf:"varint,1,opt,name=status,proto3,enum=go.micro.service.answer.SearchAnswerByHomeworkIDResponse_Status" json:"status,omitempty"`
	Msg     string                                  `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	Answers []*AnswerInfo                           `protobuf:"bytes,3,rep,name=answers,proto3" json:"answers,omitempty"`
}

func (x *SearchAnswerByHomeworkIDResponse) Reset() {
	*x = SearchAnswerByHomeworkIDResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_answer_answer_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SearchAnswerByHomeworkIDResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchAnswerByHomeworkIDResponse) ProtoMessage() {}

func (x *SearchAnswerByHomeworkIDResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_answer_answer_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchAnswerByHomeworkIDResponse.ProtoReflect.Descriptor instead.
func (*SearchAnswerByHomeworkIDResponse) Descriptor() ([]byte, []int) {
	return file_proto_answer_answer_proto_rawDescGZIP(), []int{11}
}

func (x *SearchAnswerByHomeworkIDResponse) GetStatus() SearchAnswerByHomeworkIDResponse_Status {
	if x != nil {
		return x.Status
	}
	return SearchAnswerByHomeworkIDResponse_SUCCESS
}

func (x *SearchAnswerByHomeworkIDResponse) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

func (x *SearchAnswerByHomeworkIDResponse) GetAnswers() []*AnswerInfo {
	if x != nil {
		return x.Answers
	}
	return nil
}

type SearchAnswerByStudentIDAndHomeworkIDResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status SearchAnswerByStudentIDAndHomeworkIDResponse_Status `protobuf:"varint,1,opt,name=status,proto3,enum=go.micro.service.answer.SearchAnswerByStudentIDAndHomeworkIDResponse_Status" json:"status,omitempty"`
	Msg    string                                              `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	Answer *AnswerInfo                                         `protobuf:"bytes,4,opt,name=answer,proto3" json:"answer,omitempty"`
}

func (x *SearchAnswerByStudentIDAndHomeworkIDResponse) Reset() {
	*x = SearchAnswerByStudentIDAndHomeworkIDResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_answer_answer_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SearchAnswerByStudentIDAndHomeworkIDResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchAnswerByStudentIDAndHomeworkIDResponse) ProtoMessage() {}

func (x *SearchAnswerByStudentIDAndHomeworkIDResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_answer_answer_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchAnswerByStudentIDAndHomeworkIDResponse.ProtoReflect.Descriptor instead.
func (*SearchAnswerByStudentIDAndHomeworkIDResponse) Descriptor() ([]byte, []int) {
	return file_proto_answer_answer_proto_rawDescGZIP(), []int{12}
}

func (x *SearchAnswerByStudentIDAndHomeworkIDResponse) GetStatus() SearchAnswerByStudentIDAndHomeworkIDResponse_Status {
	if x != nil {
		return x.Status
	}
	return SearchAnswerByStudentIDAndHomeworkIDResponse_SUCCESS
}

func (x *SearchAnswerByStudentIDAndHomeworkIDResponse) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

func (x *SearchAnswerByStudentIDAndHomeworkIDResponse) GetAnswer() *AnswerInfo {
	if x != nil {
		return x.Answer
	}
	return nil
}

var File_proto_answer_answer_proto protoreflect.FileDescriptor

var file_proto_answer_answer_proto_rawDesc = []byte{
	0x0a, 0x19, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x61, 0x6e, 0x73, 0x77, 0x65, 0x72, 0x2f, 0x61,
	0x6e, 0x73, 0x77, 0x65, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x17, 0x67, 0x6f, 0x2e,
	0x6d, 0x69, 0x63, 0x72, 0x6f, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x61, 0x6e,
	0x73, 0x77, 0x65, 0x72, 0x22, 0xab, 0x01, 0x0a, 0x11, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x41,
	0x6e, 0x73, 0x77, 0x65, 0x72, 0x50, 0x61, 0x72, 0x61, 0x6d, 0x12, 0x1e, 0x0a, 0x0a, 0x68, 0x6f,
	0x6d, 0x65, 0x77, 0x6f, 0x72, 0x6b, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0a,
	0x68, 0x6f, 0x6d, 0x65, 0x77, 0x6f, 0x72, 0x6b, 0x49, 0x44, 0x12, 0x1c, 0x0a, 0x09, 0x73, 0x74,
	0x75, 0x64, 0x65, 0x6e, 0x74, 0x49, 0x44, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x09, 0x73,
	0x74, 0x75, 0x64, 0x65, 0x6e, 0x74, 0x49, 0x44, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74,
	0x75, 0x73, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73,
	0x12, 0x1f, 0x0a, 0x0b, 0x63, 0x6f, 0x6d, 0x6d, 0x69, 0x74, 0x5f, 0x74, 0x69, 0x6d, 0x65, 0x18,
	0x04, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0a, 0x63, 0x6f, 0x6d, 0x6d, 0x69, 0x74, 0x54, 0x69, 0x6d,
	0x65, 0x12, 0x1f, 0x0a, 0x0b, 0x61, 0x6e, 0x73, 0x77, 0x65, 0x72, 0x5f, 0x6a, 0x73, 0x6f, 0x6e,
	0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x61, 0x6e, 0x73, 0x77, 0x65, 0x72, 0x4a, 0x73,
	0x6f, 0x6e, 0x22, 0x26, 0x0a, 0x08, 0x41, 0x6e, 0x73, 0x77, 0x65, 0x72, 0x49, 0x44, 0x12, 0x1a,
	0x0a, 0x08, 0x41, 0x6e, 0x73, 0x77, 0x65, 0x72, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05,
	0x52, 0x08, 0x41, 0x6e, 0x73, 0x77, 0x65, 0x72, 0x49, 0x44, 0x22, 0xc0, 0x01, 0x0a, 0x0a, 0x41,
	0x6e, 0x73, 0x77, 0x65, 0x72, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x1a, 0x0a, 0x08, 0x41, 0x6e, 0x73,
	0x77, 0x65, 0x72, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x08, 0x41, 0x6e, 0x73,
	0x77, 0x65, 0x72, 0x49, 0x44, 0x12, 0x1e, 0x0a, 0x0a, 0x68, 0x6f, 0x6d, 0x65, 0x77, 0x6f, 0x72,
	0x6b, 0x49, 0x44, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0a, 0x68, 0x6f, 0x6d, 0x65, 0x77,
	0x6f, 0x72, 0x6b, 0x49, 0x44, 0x12, 0x1c, 0x0a, 0x09, 0x73, 0x74, 0x75, 0x64, 0x65, 0x6e, 0x74,
	0x49, 0x44, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x09, 0x73, 0x74, 0x75, 0x64, 0x65, 0x6e,
	0x74, 0x49, 0x44, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x04, 0x20,
	0x01, 0x28, 0x05, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x1f, 0x0a, 0x0b, 0x63,
	0x6f, 0x6d, 0x6d, 0x69, 0x74, 0x5f, 0x74, 0x69, 0x6d, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x03,
	0x52, 0x0a, 0x63, 0x6f, 0x6d, 0x6d, 0x69, 0x74, 0x54, 0x69, 0x6d, 0x65, 0x12, 0x1f, 0x0a, 0x0b,
	0x61, 0x6e, 0x73, 0x77, 0x65, 0x72, 0x5f, 0x6a, 0x73, 0x6f, 0x6e, 0x18, 0x06, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x0a, 0x61, 0x6e, 0x73, 0x77, 0x65, 0x72, 0x4a, 0x73, 0x6f, 0x6e, 0x22, 0x29, 0x0a,
	0x09, 0x53, 0x74, 0x75, 0x64, 0x65, 0x6e, 0x74, 0x49, 0x44, 0x12, 0x1c, 0x0a, 0x09, 0x53, 0x74,
	0x75, 0x64, 0x65, 0x6e, 0x74, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x09, 0x53,
	0x74, 0x75, 0x64, 0x65, 0x6e, 0x74, 0x49, 0x44, 0x22, 0x2c, 0x0a, 0x0a, 0x48, 0x6f, 0x6d, 0x65,
	0x77, 0x6f, 0x72, 0x6b, 0x49, 0x44, 0x12, 0x1e, 0x0a, 0x0a, 0x48, 0x6f, 0x6d, 0x65, 0x77, 0x6f,
	0x72, 0x6b, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0a, 0x48, 0x6f, 0x6d, 0x65,
	0x77, 0x6f, 0x72, 0x6b, 0x49, 0x44, 0x22, 0x56, 0x0a, 0x16, 0x53, 0x74, 0x75, 0x64, 0x65, 0x6e,
	0x74, 0x49, 0x44, 0x41, 0x6e, 0x64, 0x48, 0x6f, 0x6d, 0x65, 0x77, 0x6f, 0x72, 0x6b, 0x49, 0x44,
	0x12, 0x1c, 0x0a, 0x09, 0x53, 0x74, 0x75, 0x64, 0x65, 0x6e, 0x74, 0x49, 0x44, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x05, 0x52, 0x09, 0x53, 0x74, 0x75, 0x64, 0x65, 0x6e, 0x74, 0x49, 0x44, 0x12, 0x1e,
	0x0a, 0x0a, 0x48, 0x6f, 0x6d, 0x65, 0x77, 0x6f, 0x72, 0x6b, 0x49, 0x44, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x05, 0x52, 0x0a, 0x48, 0x6f, 0x6d, 0x65, 0x77, 0x6f, 0x72, 0x6b, 0x49, 0x44, 0x22, 0xbd,
	0x01, 0x0a, 0x14, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x41, 0x6e, 0x73, 0x77, 0x65, 0x72, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x4c, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75,
	0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x34, 0x2e, 0x67, 0x6f, 0x2e, 0x6d, 0x69, 0x63,
	0x72, 0x6f, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x61, 0x6e, 0x73, 0x77, 0x65,
	0x72, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x41, 0x6e, 0x73, 0x77, 0x65, 0x72, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x2e, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x06, 0x73,
	0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x10, 0x0a, 0x03, 0x6d, 0x73, 0x67, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x03, 0x6d, 0x73, 0x67, 0x12, 0x1a, 0x0a, 0x08, 0x41, 0x6e, 0x73, 0x77, 0x65,
	0x72, 0x49, 0x44, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x08, 0x41, 0x6e, 0x73, 0x77, 0x65,
	0x72, 0x49, 0x44, 0x22, 0x29, 0x0a, 0x06, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x0b, 0x0a,
	0x07, 0x53, 0x55, 0x43, 0x43, 0x45, 0x53, 0x53, 0x10, 0x00, 0x12, 0x12, 0x0a, 0x05, 0x45, 0x52,
	0x52, 0x4f, 0x52, 0x10, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0x01, 0x22, 0xa1,
	0x01, 0x0a, 0x14, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x41, 0x6e, 0x73, 0x77, 0x65, 0x72, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x4c, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75,
	0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x34, 0x2e, 0x67, 0x6f, 0x2e, 0x6d, 0x69, 0x63,
	0x72, 0x6f, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x61, 0x6e, 0x73, 0x77, 0x65,
	0x72, 0x2e, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x41, 0x6e, 0x73, 0x77, 0x65, 0x72, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x2e, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x06, 0x73,
	0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x10, 0x0a, 0x03, 0x6d, 0x73, 0x67, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x03, 0x6d, 0x73, 0x67, 0x22, 0x29, 0x0a, 0x06, 0x53, 0x74, 0x61, 0x74, 0x75,
	0x73, 0x12, 0x0b, 0x0a, 0x07, 0x53, 0x55, 0x43, 0x43, 0x45, 0x53, 0x53, 0x10, 0x00, 0x12, 0x12,
	0x0a, 0x05, 0x45, 0x52, 0x52, 0x4f, 0x52, 0x10, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff,
	0xff, 0x01, 0x22, 0xa1, 0x01, 0x0a, 0x14, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x41, 0x6e, 0x73,
	0x77, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x4c, 0x0a, 0x06, 0x73,
	0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x34, 0x2e, 0x67, 0x6f,
	0x2e, 0x6d, 0x69, 0x63, 0x72, 0x6f, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x61,
	0x6e, 0x73, 0x77, 0x65, 0x72, 0x2e, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x41, 0x6e, 0x73, 0x77,
	0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x2e, 0x53, 0x74, 0x61, 0x74, 0x75,
	0x73, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x10, 0x0a, 0x03, 0x6d, 0x73, 0x67,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6d, 0x73, 0x67, 0x22, 0x29, 0x0a, 0x06, 0x53,
	0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x0b, 0x0a, 0x07, 0x53, 0x55, 0x43, 0x43, 0x45, 0x53, 0x53,
	0x10, 0x00, 0x12, 0x12, 0x0a, 0x05, 0x45, 0x52, 0x52, 0x4f, 0x52, 0x10, 0xff, 0xff, 0xff, 0xff,
	0xff, 0xff, 0xff, 0xff, 0xff, 0x01, 0x22, 0xde, 0x01, 0x0a, 0x14, 0x53, 0x65, 0x61, 0x72, 0x63,
	0x68, 0x41, 0x6e, 0x73, 0x77, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12,
	0x4c, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32,
	0x34, 0x2e, 0x67, 0x6f, 0x2e, 0x6d, 0x69, 0x63, 0x72, 0x6f, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x69,
	0x63, 0x65, 0x2e, 0x61, 0x6e, 0x73, 0x77, 0x65, 0x72, 0x2e, 0x53, 0x65, 0x61, 0x72, 0x63, 0x68,
	0x41, 0x6e, 0x73, 0x77, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x2e, 0x53,
	0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x10, 0x0a,
	0x03, 0x6d, 0x73, 0x67, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6d, 0x73, 0x67, 0x12,
	0x3b, 0x0a, 0x06, 0x61, 0x6e, 0x73, 0x77, 0x65, 0x72, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x23, 0x2e, 0x67, 0x6f, 0x2e, 0x6d, 0x69, 0x63, 0x72, 0x6f, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x69,
	0x63, 0x65, 0x2e, 0x61, 0x6e, 0x73, 0x77, 0x65, 0x72, 0x2e, 0x41, 0x6e, 0x73, 0x77, 0x65, 0x72,
	0x49, 0x6e, 0x66, 0x6f, 0x52, 0x06, 0x61, 0x6e, 0x73, 0x77, 0x65, 0x72, 0x22, 0x29, 0x0a, 0x06,
	0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x0b, 0x0a, 0x07, 0x53, 0x55, 0x43, 0x43, 0x45, 0x53,
	0x53, 0x10, 0x00, 0x12, 0x12, 0x0a, 0x05, 0x45, 0x52, 0x52, 0x4f, 0x52, 0x10, 0xff, 0xff, 0xff,
	0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0x01, 0x22, 0xf6, 0x01, 0x0a, 0x1f, 0x53, 0x65, 0x61, 0x72,
	0x63, 0x68, 0x41, 0x6e, 0x73, 0x77, 0x65, 0x72, 0x42, 0x79, 0x53, 0x74, 0x75, 0x64, 0x65, 0x6e,
	0x74, 0x49, 0x44, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x57, 0x0a, 0x06, 0x73,
	0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x3f, 0x2e, 0x67, 0x6f,
	0x2e, 0x6d, 0x69, 0x63, 0x72, 0x6f, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x61,
	0x6e, 0x73, 0x77, 0x65, 0x72, 0x2e, 0x53, 0x65, 0x61, 0x72, 0x63, 0x68, 0x41, 0x6e, 0x73, 0x77,
	0x65, 0x72, 0x42, 0x79, 0x53, 0x74, 0x75, 0x64, 0x65, 0x6e, 0x74, 0x49, 0x44, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x2e, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x06, 0x73, 0x74,
	0x61, 0x74, 0x75, 0x73, 0x12, 0x10, 0x0a, 0x03, 0x6d, 0x73, 0x67, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x03, 0x6d, 0x73, 0x67, 0x12, 0x3d, 0x0a, 0x07, 0x61, 0x6e, 0x73, 0x77, 0x65, 0x72,
	0x73, 0x18, 0x03, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x23, 0x2e, 0x67, 0x6f, 0x2e, 0x6d, 0x69, 0x63,
	0x72, 0x6f, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x61, 0x6e, 0x73, 0x77, 0x65,
	0x72, 0x2e, 0x41, 0x6e, 0x73, 0x77, 0x65, 0x72, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x07, 0x61, 0x6e,
	0x73, 0x77, 0x65, 0x72, 0x73, 0x22, 0x29, 0x0a, 0x06, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12,
	0x0b, 0x0a, 0x07, 0x53, 0x55, 0x43, 0x43, 0x45, 0x53, 0x53, 0x10, 0x00, 0x12, 0x12, 0x0a, 0x05,
	0x45, 0x52, 0x52, 0x4f, 0x52, 0x10, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0x01,
	0x22, 0xf8, 0x01, 0x0a, 0x20, 0x53, 0x65, 0x61, 0x72, 0x63, 0x68, 0x41, 0x6e, 0x73, 0x77, 0x65,
	0x72, 0x42, 0x79, 0x48, 0x6f, 0x6d, 0x65, 0x77, 0x6f, 0x72, 0x6b, 0x49, 0x44, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x58, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x40, 0x2e, 0x67, 0x6f, 0x2e, 0x6d, 0x69, 0x63, 0x72, 0x6f,
	0x2e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x61, 0x6e, 0x73, 0x77, 0x65, 0x72, 0x2e,
	0x53, 0x65, 0x61, 0x72, 0x63, 0x68, 0x41, 0x6e, 0x73, 0x77, 0x65, 0x72, 0x42, 0x79, 0x48, 0x6f,
	0x6d, 0x65, 0x77, 0x6f, 0x72, 0x6b, 0x49, 0x44, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x2e, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12,
	0x10, 0x0a, 0x03, 0x6d, 0x73, 0x67, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6d, 0x73,
	0x67, 0x12, 0x3d, 0x0a, 0x07, 0x61, 0x6e, 0x73, 0x77, 0x65, 0x72, 0x73, 0x18, 0x03, 0x20, 0x03,
	0x28, 0x0b, 0x32, 0x23, 0x2e, 0x67, 0x6f, 0x2e, 0x6d, 0x69, 0x63, 0x72, 0x6f, 0x2e, 0x73, 0x65,
	0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x61, 0x6e, 0x73, 0x77, 0x65, 0x72, 0x2e, 0x41, 0x6e, 0x73,
	0x77, 0x65, 0x72, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x07, 0x61, 0x6e, 0x73, 0x77, 0x65, 0x72, 0x73,
	0x22, 0x29, 0x0a, 0x06, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x0b, 0x0a, 0x07, 0x53, 0x55,
	0x43, 0x43, 0x45, 0x53, 0x53, 0x10, 0x00, 0x12, 0x12, 0x0a, 0x05, 0x45, 0x52, 0x52, 0x4f, 0x52,
	0x10, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0x01, 0x22, 0x85, 0x02, 0x0a, 0x2c,
	0x53, 0x65, 0x61, 0x72, 0x63, 0x68, 0x41, 0x6e, 0x73, 0x77, 0x65, 0x72, 0x42, 0x79, 0x53, 0x74,
	0x75, 0x64, 0x65, 0x6e, 0x74, 0x49, 0x44, 0x41, 0x6e, 0x64, 0x48, 0x6f, 0x6d, 0x65, 0x77, 0x6f,
	0x72, 0x6b, 0x49, 0x44, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x64, 0x0a, 0x06,
	0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x4c, 0x2e, 0x67,
	0x6f, 0x2e, 0x6d, 0x69, 0x63, 0x72, 0x6f, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e,
	0x61, 0x6e, 0x73, 0x77, 0x65, 0x72, 0x2e, 0x53, 0x65, 0x61, 0x72, 0x63, 0x68, 0x41, 0x6e, 0x73,
	0x77, 0x65, 0x72, 0x42, 0x79, 0x53, 0x74, 0x75, 0x64, 0x65, 0x6e, 0x74, 0x49, 0x44, 0x41, 0x6e,
	0x64, 0x48, 0x6f, 0x6d, 0x65, 0x77, 0x6f, 0x72, 0x6b, 0x49, 0x44, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x2e, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74,
	0x75, 0x73, 0x12, 0x10, 0x0a, 0x03, 0x6d, 0x73, 0x67, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x03, 0x6d, 0x73, 0x67, 0x12, 0x3b, 0x0a, 0x06, 0x61, 0x6e, 0x73, 0x77, 0x65, 0x72, 0x18, 0x04,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x23, 0x2e, 0x67, 0x6f, 0x2e, 0x6d, 0x69, 0x63, 0x72, 0x6f, 0x2e,
	0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x61, 0x6e, 0x73, 0x77, 0x65, 0x72, 0x2e, 0x41,
	0x6e, 0x73, 0x77, 0x65, 0x72, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x06, 0x61, 0x6e, 0x73, 0x77, 0x65,
	0x72, 0x22, 0x20, 0x0a, 0x06, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x0b, 0x0a, 0x07, 0x53,
	0x55, 0x43, 0x43, 0x45, 0x53, 0x53, 0x10, 0x00, 0x12, 0x09, 0x0a, 0x05, 0x45, 0x52, 0x52, 0x4f,
	0x52, 0x10, 0x01, 0x32, 0xc6, 0x06, 0x0a, 0x0d, 0x41, 0x6e, 0x73, 0x77, 0x65, 0x72, 0x53, 0x65,
	0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x6b, 0x0a, 0x0c, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x41,
	0x6e, 0x73, 0x77, 0x65, 0x72, 0x12, 0x2a, 0x2e, 0x67, 0x6f, 0x2e, 0x6d, 0x69, 0x63, 0x72, 0x6f,
	0x2e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x61, 0x6e, 0x73, 0x77, 0x65, 0x72, 0x2e,
	0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x41, 0x6e, 0x73, 0x77, 0x65, 0x72, 0x50, 0x61, 0x72, 0x61,
	0x6d, 0x1a, 0x2d, 0x2e, 0x67, 0x6f, 0x2e, 0x6d, 0x69, 0x63, 0x72, 0x6f, 0x2e, 0x73, 0x65, 0x72,
	0x76, 0x69, 0x63, 0x65, 0x2e, 0x61, 0x6e, 0x73, 0x77, 0x65, 0x72, 0x2e, 0x43, 0x72, 0x65, 0x61,
	0x74, 0x65, 0x41, 0x6e, 0x73, 0x77, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x22, 0x00, 0x12, 0x62, 0x0a, 0x0c, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x41, 0x6e, 0x73, 0x77,
	0x65, 0x72, 0x12, 0x21, 0x2e, 0x67, 0x6f, 0x2e, 0x6d, 0x69, 0x63, 0x72, 0x6f, 0x2e, 0x73, 0x65,
	0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x61, 0x6e, 0x73, 0x77, 0x65, 0x72, 0x2e, 0x41, 0x6e, 0x73,
	0x77, 0x65, 0x72, 0x49, 0x44, 0x1a, 0x2d, 0x2e, 0x67, 0x6f, 0x2e, 0x6d, 0x69, 0x63, 0x72, 0x6f,
	0x2e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x61, 0x6e, 0x73, 0x77, 0x65, 0x72, 0x2e,
	0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x41, 0x6e, 0x73, 0x77, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x64, 0x0a, 0x0c, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65,
	0x41, 0x6e, 0x73, 0x77, 0x65, 0x72, 0x12, 0x23, 0x2e, 0x67, 0x6f, 0x2e, 0x6d, 0x69, 0x63, 0x72,
	0x6f, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x61, 0x6e, 0x73, 0x77, 0x65, 0x72,
	0x2e, 0x41, 0x6e, 0x73, 0x77, 0x65, 0x72, 0x49, 0x6e, 0x66, 0x6f, 0x1a, 0x2d, 0x2e, 0x67, 0x6f,
	0x2e, 0x6d, 0x69, 0x63, 0x72, 0x6f, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x61,
	0x6e, 0x73, 0x77, 0x65, 0x72, 0x2e, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x41, 0x6e, 0x73, 0x77,
	0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x62, 0x0a, 0x0c,
	0x53, 0x65, 0x61, 0x72, 0x63, 0x68, 0x41, 0x6e, 0x73, 0x77, 0x65, 0x72, 0x12, 0x21, 0x2e, 0x67,
	0x6f, 0x2e, 0x6d, 0x69, 0x63, 0x72, 0x6f, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e,
	0x61, 0x6e, 0x73, 0x77, 0x65, 0x72, 0x2e, 0x41, 0x6e, 0x73, 0x77, 0x65, 0x72, 0x49, 0x44, 0x1a,
	0x2d, 0x2e, 0x67, 0x6f, 0x2e, 0x6d, 0x69, 0x63, 0x72, 0x6f, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x69,
	0x63, 0x65, 0x2e, 0x61, 0x6e, 0x73, 0x77, 0x65, 0x72, 0x2e, 0x53, 0x65, 0x61, 0x72, 0x63, 0x68,
	0x41, 0x6e, 0x73, 0x77, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00,
	0x12, 0x79, 0x0a, 0x17, 0x53, 0x65, 0x61, 0x72, 0x63, 0x68, 0x41, 0x6e, 0x73, 0x77, 0x65, 0x72,
	0x42, 0x79, 0x53, 0x74, 0x75, 0x64, 0x65, 0x6e, 0x74, 0x49, 0x44, 0x12, 0x22, 0x2e, 0x67, 0x6f,
	0x2e, 0x6d, 0x69, 0x63, 0x72, 0x6f, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x61,
	0x6e, 0x73, 0x77, 0x65, 0x72, 0x2e, 0x53, 0x74, 0x75, 0x64, 0x65, 0x6e, 0x74, 0x49, 0x44, 0x1a,
	0x38, 0x2e, 0x67, 0x6f, 0x2e, 0x6d, 0x69, 0x63, 0x72, 0x6f, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x69,
	0x63, 0x65, 0x2e, 0x61, 0x6e, 0x73, 0x77, 0x65, 0x72, 0x2e, 0x53, 0x65, 0x61, 0x72, 0x63, 0x68,
	0x41, 0x6e, 0x73, 0x77, 0x65, 0x72, 0x42, 0x79, 0x53, 0x74, 0x75, 0x64, 0x65, 0x6e, 0x74, 0x49,
	0x44, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x7c, 0x0a, 0x18, 0x53,
	0x65, 0x61, 0x72, 0x63, 0x68, 0x41, 0x6e, 0x73, 0x77, 0x65, 0x72, 0x42, 0x79, 0x48, 0x6f, 0x6d,
	0x65, 0x77, 0x6f, 0x72, 0x6b, 0x49, 0x44, 0x12, 0x23, 0x2e, 0x67, 0x6f, 0x2e, 0x6d, 0x69, 0x63,
	0x72, 0x6f, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x61, 0x6e, 0x73, 0x77, 0x65,
	0x72, 0x2e, 0x48, 0x6f, 0x6d, 0x65, 0x77, 0x6f, 0x72, 0x6b, 0x49, 0x44, 0x1a, 0x39, 0x2e, 0x67,
	0x6f, 0x2e, 0x6d, 0x69, 0x63, 0x72, 0x6f, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e,
	0x61, 0x6e, 0x73, 0x77, 0x65, 0x72, 0x2e, 0x53, 0x65, 0x61, 0x72, 0x63, 0x68, 0x41, 0x6e, 0x73,
	0x77, 0x65, 0x72, 0x42, 0x79, 0x48, 0x6f, 0x6d, 0x65, 0x77, 0x6f, 0x72, 0x6b, 0x49, 0x44, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0xa0, 0x01, 0x0a, 0x24, 0x53, 0x65,
	0x61, 0x72, 0x63, 0x68, 0x41, 0x6e, 0x73, 0x77, 0x65, 0x72, 0x42, 0x79, 0x53, 0x74, 0x75, 0x64,
	0x65, 0x6e, 0x74, 0x49, 0x44, 0x41, 0x6e, 0x64, 0x48, 0x6f, 0x6d, 0x65, 0x77, 0x6f, 0x72, 0x6b,
	0x49, 0x44, 0x12, 0x2f, 0x2e, 0x67, 0x6f, 0x2e, 0x6d, 0x69, 0x63, 0x72, 0x6f, 0x2e, 0x73, 0x65,
	0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x61, 0x6e, 0x73, 0x77, 0x65, 0x72, 0x2e, 0x53, 0x74, 0x75,
	0x64, 0x65, 0x6e, 0x74, 0x49, 0x44, 0x41, 0x6e, 0x64, 0x48, 0x6f, 0x6d, 0x65, 0x77, 0x6f, 0x72,
	0x6b, 0x49, 0x44, 0x1a, 0x45, 0x2e, 0x67, 0x6f, 0x2e, 0x6d, 0x69, 0x63, 0x72, 0x6f, 0x2e, 0x73,
	0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x61, 0x6e, 0x73, 0x77, 0x65, 0x72, 0x2e, 0x53, 0x65,
	0x61, 0x72, 0x63, 0x68, 0x41, 0x6e, 0x73, 0x77, 0x65, 0x72, 0x42, 0x79, 0x53, 0x74, 0x75, 0x64,
	0x65, 0x6e, 0x74, 0x49, 0x44, 0x41, 0x6e, 0x64, 0x48, 0x6f, 0x6d, 0x65, 0x77, 0x6f, 0x72, 0x6b,
	0x49, 0x44, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x42, 0x0e, 0x5a, 0x0c,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x61, 0x6e, 0x73, 0x77, 0x65, 0x72, 0x62, 0x06, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_proto_answer_answer_proto_rawDescOnce sync.Once
	file_proto_answer_answer_proto_rawDescData = file_proto_answer_answer_proto_rawDesc
)

func file_proto_answer_answer_proto_rawDescGZIP() []byte {
	file_proto_answer_answer_proto_rawDescOnce.Do(func() {
		file_proto_answer_answer_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_answer_answer_proto_rawDescData)
	})
	return file_proto_answer_answer_proto_rawDescData
}

var file_proto_answer_answer_proto_enumTypes = make([]protoimpl.EnumInfo, 7)
var file_proto_answer_answer_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_proto_answer_answer_proto_goTypes = []interface{}{
	(CreateAnswerResponse_Status)(0),                         // 0: go.micro.service.answer.CreateAnswerResponse.Status
	(DeleteAnswerResponse_Status)(0),                         // 1: go.micro.service.answer.DeleteAnswerResponse.Status
	(UpdateAnswerResponse_Status)(0),                         // 2: go.micro.service.answer.UpdateAnswerResponse.Status
	(SearchAnswerResponse_Status)(0),                         // 3: go.micro.service.answer.SearchAnswerResponse.Status
	(SearchAnswerByStudentIDResponse_Status)(0),              // 4: go.micro.service.answer.SearchAnswerByStudentIDResponse.Status
	(SearchAnswerByHomeworkIDResponse_Status)(0),             // 5: go.micro.service.answer.SearchAnswerByHomeworkIDResponse.Status
	(SearchAnswerByStudentIDAndHomeworkIDResponse_Status)(0), // 6: go.micro.service.answer.SearchAnswerByStudentIDAndHomeworkIDResponse.Status
	(*CreateAnswerParam)(nil),                                // 7: go.micro.service.answer.CreateAnswerParam
	(*AnswerID)(nil),                                         // 8: go.micro.service.answer.AnswerID
	(*AnswerInfo)(nil),                                       // 9: go.micro.service.answer.AnswerInfo
	(*StudentID)(nil),                                        // 10: go.micro.service.answer.StudentID
	(*HomeworkID)(nil),                                       // 11: go.micro.service.answer.HomeworkID
	(*StudentIDAndHomeworkID)(nil),                           // 12: go.micro.service.answer.StudentIDAndHomeworkID
	(*CreateAnswerResponse)(nil),                             // 13: go.micro.service.answer.CreateAnswerResponse
	(*DeleteAnswerResponse)(nil),                             // 14: go.micro.service.answer.DeleteAnswerResponse
	(*UpdateAnswerResponse)(nil),                             // 15: go.micro.service.answer.UpdateAnswerResponse
	(*SearchAnswerResponse)(nil),                             // 16: go.micro.service.answer.SearchAnswerResponse
	(*SearchAnswerByStudentIDResponse)(nil),                  // 17: go.micro.service.answer.SearchAnswerByStudentIDResponse
	(*SearchAnswerByHomeworkIDResponse)(nil),                 // 18: go.micro.service.answer.SearchAnswerByHomeworkIDResponse
	(*SearchAnswerByStudentIDAndHomeworkIDResponse)(nil),     // 19: go.micro.service.answer.SearchAnswerByStudentIDAndHomeworkIDResponse
}
var file_proto_answer_answer_proto_depIdxs = []int32{
	0,  // 0: go.micro.service.answer.CreateAnswerResponse.status:type_name -> go.micro.service.answer.CreateAnswerResponse.Status
	1,  // 1: go.micro.service.answer.DeleteAnswerResponse.status:type_name -> go.micro.service.answer.DeleteAnswerResponse.Status
	2,  // 2: go.micro.service.answer.UpdateAnswerResponse.status:type_name -> go.micro.service.answer.UpdateAnswerResponse.Status
	3,  // 3: go.micro.service.answer.SearchAnswerResponse.status:type_name -> go.micro.service.answer.SearchAnswerResponse.Status
	9,  // 4: go.micro.service.answer.SearchAnswerResponse.answer:type_name -> go.micro.service.answer.AnswerInfo
	4,  // 5: go.micro.service.answer.SearchAnswerByStudentIDResponse.status:type_name -> go.micro.service.answer.SearchAnswerByStudentIDResponse.Status
	9,  // 6: go.micro.service.answer.SearchAnswerByStudentIDResponse.answers:type_name -> go.micro.service.answer.AnswerInfo
	5,  // 7: go.micro.service.answer.SearchAnswerByHomeworkIDResponse.status:type_name -> go.micro.service.answer.SearchAnswerByHomeworkIDResponse.Status
	9,  // 8: go.micro.service.answer.SearchAnswerByHomeworkIDResponse.answers:type_name -> go.micro.service.answer.AnswerInfo
	6,  // 9: go.micro.service.answer.SearchAnswerByStudentIDAndHomeworkIDResponse.status:type_name -> go.micro.service.answer.SearchAnswerByStudentIDAndHomeworkIDResponse.Status
	9,  // 10: go.micro.service.answer.SearchAnswerByStudentIDAndHomeworkIDResponse.answer:type_name -> go.micro.service.answer.AnswerInfo
	7,  // 11: go.micro.service.answer.AnswerService.CreateAnswer:input_type -> go.micro.service.answer.CreateAnswerParam
	8,  // 12: go.micro.service.answer.AnswerService.DeleteAnswer:input_type -> go.micro.service.answer.AnswerID
	9,  // 13: go.micro.service.answer.AnswerService.UpdateAnswer:input_type -> go.micro.service.answer.AnswerInfo
	8,  // 14: go.micro.service.answer.AnswerService.SearchAnswer:input_type -> go.micro.service.answer.AnswerID
	10, // 15: go.micro.service.answer.AnswerService.SearchAnswerByStudentID:input_type -> go.micro.service.answer.StudentID
	11, // 16: go.micro.service.answer.AnswerService.SearchAnswerByHomeworkID:input_type -> go.micro.service.answer.HomeworkID
	12, // 17: go.micro.service.answer.AnswerService.SearchAnswerByStudentIDAndHomeworkID:input_type -> go.micro.service.answer.StudentIDAndHomeworkID
	13, // 18: go.micro.service.answer.AnswerService.CreateAnswer:output_type -> go.micro.service.answer.CreateAnswerResponse
	14, // 19: go.micro.service.answer.AnswerService.DeleteAnswer:output_type -> go.micro.service.answer.DeleteAnswerResponse
	15, // 20: go.micro.service.answer.AnswerService.UpdateAnswer:output_type -> go.micro.service.answer.UpdateAnswerResponse
	16, // 21: go.micro.service.answer.AnswerService.SearchAnswer:output_type -> go.micro.service.answer.SearchAnswerResponse
	17, // 22: go.micro.service.answer.AnswerService.SearchAnswerByStudentID:output_type -> go.micro.service.answer.SearchAnswerByStudentIDResponse
	18, // 23: go.micro.service.answer.AnswerService.SearchAnswerByHomeworkID:output_type -> go.micro.service.answer.SearchAnswerByHomeworkIDResponse
	19, // 24: go.micro.service.answer.AnswerService.SearchAnswerByStudentIDAndHomeworkID:output_type -> go.micro.service.answer.SearchAnswerByStudentIDAndHomeworkIDResponse
	18, // [18:25] is the sub-list for method output_type
	11, // [11:18] is the sub-list for method input_type
	11, // [11:11] is the sub-list for extension type_name
	11, // [11:11] is the sub-list for extension extendee
	0,  // [0:11] is the sub-list for field type_name
}

func init() { file_proto_answer_answer_proto_init() }
func file_proto_answer_answer_proto_init() {
	if File_proto_answer_answer_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_proto_answer_answer_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateAnswerParam); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_answer_answer_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AnswerID); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_answer_answer_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AnswerInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_answer_answer_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StudentID); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_answer_answer_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*HomeworkID); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_answer_answer_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StudentIDAndHomeworkID); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_answer_answer_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateAnswerResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_answer_answer_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteAnswerResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_answer_answer_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateAnswerResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_answer_answer_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SearchAnswerResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_answer_answer_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SearchAnswerByStudentIDResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_answer_answer_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SearchAnswerByHomeworkIDResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_answer_answer_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SearchAnswerByStudentIDAndHomeworkIDResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_answer_answer_proto_rawDesc,
			NumEnums:      7,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_answer_answer_proto_goTypes,
		DependencyIndexes: file_proto_answer_answer_proto_depIdxs,
		EnumInfos:         file_proto_answer_answer_proto_enumTypes,
		MessageInfos:      file_proto_answer_answer_proto_msgTypes,
	}.Build()
	File_proto_answer_answer_proto = out.File
	file_proto_answer_answer_proto_rawDesc = nil
	file_proto_answer_answer_proto_goTypes = nil
	file_proto_answer_answer_proto_depIdxs = nil
}
