//声明proto本版

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0
// 	protoc        v3.14.0
// source: proto/homework/homework.proto

//服务名

package homework

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type AssignHomeworkResponse_Status int32

const (
	AssignHomeworkResponse_SUCCESS AssignHomeworkResponse_Status = 0
	AssignHomeworkResponse_ERROR   AssignHomeworkResponse_Status = -1
)

// Enum value maps for AssignHomeworkResponse_Status.
var (
	AssignHomeworkResponse_Status_name = map[int32]string{
		0:  "SUCCESS",
		-1: "ERROR",
	}
	AssignHomeworkResponse_Status_value = map[string]int32{
		"SUCCESS": 0,
		"ERROR":   -1,
	}
)

func (x AssignHomeworkResponse_Status) Enum() *AssignHomeworkResponse_Status {
	p := new(AssignHomeworkResponse_Status)
	*p = x
	return p
}

func (x AssignHomeworkResponse_Status) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AssignHomeworkResponse_Status) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_homework_homework_proto_enumTypes[0].Descriptor()
}

func (AssignHomeworkResponse_Status) Type() protoreflect.EnumType {
	return &file_proto_homework_homework_proto_enumTypes[0]
}

func (x AssignHomeworkResponse_Status) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use AssignHomeworkResponse_Status.Descriptor instead.
func (AssignHomeworkResponse_Status) EnumDescriptor() ([]byte, []int) {
	return file_proto_homework_homework_proto_rawDescGZIP(), []int{4, 0}
}

type DeleteHomeworkResponse_Status int32

const (
	DeleteHomeworkResponse_SUCCESS DeleteHomeworkResponse_Status = 0
	DeleteHomeworkResponse_ERROR   DeleteHomeworkResponse_Status = -1
)

// Enum value maps for DeleteHomeworkResponse_Status.
var (
	DeleteHomeworkResponse_Status_name = map[int32]string{
		0:  "SUCCESS",
		-1: "ERROR",
	}
	DeleteHomeworkResponse_Status_value = map[string]int32{
		"SUCCESS": 0,
		"ERROR":   -1,
	}
)

func (x DeleteHomeworkResponse_Status) Enum() *DeleteHomeworkResponse_Status {
	p := new(DeleteHomeworkResponse_Status)
	*p = x
	return p
}

func (x DeleteHomeworkResponse_Status) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (DeleteHomeworkResponse_Status) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_homework_homework_proto_enumTypes[1].Descriptor()
}

func (DeleteHomeworkResponse_Status) Type() protoreflect.EnumType {
	return &file_proto_homework_homework_proto_enumTypes[1]
}

func (x DeleteHomeworkResponse_Status) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use DeleteHomeworkResponse_Status.Descriptor instead.
func (DeleteHomeworkResponse_Status) EnumDescriptor() ([]byte, []int) {
	return file_proto_homework_homework_proto_rawDescGZIP(), []int{5, 0}
}

type UpdateHomeworkResponse_Status int32

const (
	UpdateHomeworkResponse_SUCCESS UpdateHomeworkResponse_Status = 0
	UpdateHomeworkResponse_ERROR   UpdateHomeworkResponse_Status = -1
)

// Enum value maps for UpdateHomeworkResponse_Status.
var (
	UpdateHomeworkResponse_Status_name = map[int32]string{
		0:  "SUCCESS",
		-1: "ERROR",
	}
	UpdateHomeworkResponse_Status_value = map[string]int32{
		"SUCCESS": 0,
		"ERROR":   -1,
	}
)

func (x UpdateHomeworkResponse_Status) Enum() *UpdateHomeworkResponse_Status {
	p := new(UpdateHomeworkResponse_Status)
	*p = x
	return p
}

func (x UpdateHomeworkResponse_Status) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (UpdateHomeworkResponse_Status) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_homework_homework_proto_enumTypes[2].Descriptor()
}

func (UpdateHomeworkResponse_Status) Type() protoreflect.EnumType {
	return &file_proto_homework_homework_proto_enumTypes[2]
}

func (x UpdateHomeworkResponse_Status) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use UpdateHomeworkResponse_Status.Descriptor instead.
func (UpdateHomeworkResponse_Status) EnumDescriptor() ([]byte, []int) {
	return file_proto_homework_homework_proto_rawDescGZIP(), []int{6, 0}
}

type SearchHomeworkResponse_Status int32

const (
	SearchHomeworkResponse_SUCCESS SearchHomeworkResponse_Status = 0
	SearchHomeworkResponse_ERROR   SearchHomeworkResponse_Status = -1
)

// Enum value maps for SearchHomeworkResponse_Status.
var (
	SearchHomeworkResponse_Status_name = map[int32]string{
		0:  "SUCCESS",
		-1: "ERROR",
	}
	SearchHomeworkResponse_Status_value = map[string]int32{
		"SUCCESS": 0,
		"ERROR":   -1,
	}
)

func (x SearchHomeworkResponse_Status) Enum() *SearchHomeworkResponse_Status {
	p := new(SearchHomeworkResponse_Status)
	*p = x
	return p
}

func (x SearchHomeworkResponse_Status) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SearchHomeworkResponse_Status) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_homework_homework_proto_enumTypes[3].Descriptor()
}

func (SearchHomeworkResponse_Status) Type() protoreflect.EnumType {
	return &file_proto_homework_homework_proto_enumTypes[3]
}

func (x SearchHomeworkResponse_Status) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SearchHomeworkResponse_Status.Descriptor instead.
func (SearchHomeworkResponse_Status) EnumDescriptor() ([]byte, []int) {
	return file_proto_homework_homework_proto_rawDescGZIP(), []int{7, 0}
}

type SearchHomeworkByUserIDResponse_Status int32

const (
	SearchHomeworkByUserIDResponse_SUCCESS SearchHomeworkByUserIDResponse_Status = 0
	SearchHomeworkByUserIDResponse_ERROR   SearchHomeworkByUserIDResponse_Status = -1
)

// Enum value maps for SearchHomeworkByUserIDResponse_Status.
var (
	SearchHomeworkByUserIDResponse_Status_name = map[int32]string{
		0:  "SUCCESS",
		-1: "ERROR",
	}
	SearchHomeworkByUserIDResponse_Status_value = map[string]int32{
		"SUCCESS": 0,
		"ERROR":   -1,
	}
)

func (x SearchHomeworkByUserIDResponse_Status) Enum() *SearchHomeworkByUserIDResponse_Status {
	p := new(SearchHomeworkByUserIDResponse_Status)
	*p = x
	return p
}

func (x SearchHomeworkByUserIDResponse_Status) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SearchHomeworkByUserIDResponse_Status) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_homework_homework_proto_enumTypes[4].Descriptor()
}

func (SearchHomeworkByUserIDResponse_Status) Type() protoreflect.EnumType {
	return &file_proto_homework_homework_proto_enumTypes[4]
}

func (x SearchHomeworkByUserIDResponse_Status) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SearchHomeworkByUserIDResponse_Status.Descriptor instead.
func (SearchHomeworkByUserIDResponse_Status) EnumDescriptor() ([]byte, []int) {
	return file_proto_homework_homework_proto_rawDescGZIP(), []int{8, 0}
}

//Parameter protocol
type AssignHomeworkParam struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CourseID    int32  `protobuf:"varint,1,opt,name=courseID,proto3" json:"courseID,omitempty"`
	UserID      int32  `protobuf:"varint,2,opt,name=userID,proto3" json:"userID,omitempty"`
	StartTime   int64  `protobuf:"varint,3,opt,name=startTime,proto3" json:"startTime,omitempty"`
	EndTime     int64  `protobuf:"varint,4,opt,name=endTime,proto3" json:"endTime,omitempty"`
	Title       string `protobuf:"bytes,5,opt,name=title,proto3" json:"title,omitempty"`
	State       int32  `protobuf:"varint,6,opt,name=state,proto3" json:"state,omitempty"`
	Description string `protobuf:"bytes,7,opt,name=description,proto3" json:"description,omitempty"`
	Content     string `protobuf:"bytes,8,opt,name=content,proto3" json:"content,omitempty"`
}

func (x *AssignHomeworkParam) Reset() {
	*x = AssignHomeworkParam{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_homework_homework_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AssignHomeworkParam) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AssignHomeworkParam) ProtoMessage() {}

func (x *AssignHomeworkParam) ProtoReflect() protoreflect.Message {
	mi := &file_proto_homework_homework_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AssignHomeworkParam.ProtoReflect.Descriptor instead.
func (*AssignHomeworkParam) Descriptor() ([]byte, []int) {
	return file_proto_homework_homework_proto_rawDescGZIP(), []int{0}
}

func (x *AssignHomeworkParam) GetCourseID() int32 {
	if x != nil {
		return x.CourseID
	}
	return 0
}

func (x *AssignHomeworkParam) GetUserID() int32 {
	if x != nil {
		return x.UserID
	}
	return 0
}

func (x *AssignHomeworkParam) GetStartTime() int64 {
	if x != nil {
		return x.StartTime
	}
	return 0
}

func (x *AssignHomeworkParam) GetEndTime() int64 {
	if x != nil {
		return x.EndTime
	}
	return 0
}

func (x *AssignHomeworkParam) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *AssignHomeworkParam) GetState() int32 {
	if x != nil {
		return x.State
	}
	return 0
}

func (x *AssignHomeworkParam) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *AssignHomeworkParam) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

type HomeworkID struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	HomeworkID int32 `protobuf:"varint,1,opt,name=homeworkID,proto3" json:"homeworkID,omitempty"`
}

func (x *HomeworkID) Reset() {
	*x = HomeworkID{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_homework_homework_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HomeworkID) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HomeworkID) ProtoMessage() {}

func (x *HomeworkID) ProtoReflect() protoreflect.Message {
	mi := &file_proto_homework_homework_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HomeworkID.ProtoReflect.Descriptor instead.
func (*HomeworkID) Descriptor() ([]byte, []int) {
	return file_proto_homework_homework_proto_rawDescGZIP(), []int{1}
}

func (x *HomeworkID) GetHomeworkID() int32 {
	if x != nil {
		return x.HomeworkID
	}
	return 0
}

type HomeworkInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	HomeworkID  int32  `protobuf:"varint,1,opt,name=homeworkID,proto3" json:"homeworkID,omitempty"`
	CourseID    int32  `protobuf:"varint,2,opt,name=courseID,proto3" json:"courseID,omitempty"`
	UserID      int32  `protobuf:"varint,3,opt,name=userID,proto3" json:"userID,omitempty"`
	StartTime   int64  `protobuf:"varint,4,opt,name=startTime,proto3" json:"startTime,omitempty"`
	EndTime     int64  `protobuf:"varint,5,opt,name=endTime,proto3" json:"endTime,omitempty"`
	Title       string `protobuf:"bytes,6,opt,name=title,proto3" json:"title,omitempty"`
	State       int32  `protobuf:"varint,7,opt,name=state,proto3" json:"state,omitempty"`
	Description string `protobuf:"bytes,8,opt,name=description,proto3" json:"description,omitempty"`
	Content     string `protobuf:"bytes,9,opt,name=content,proto3" json:"content,omitempty"`
}

func (x *HomeworkInfo) Reset() {
	*x = HomeworkInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_homework_homework_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HomeworkInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HomeworkInfo) ProtoMessage() {}

func (x *HomeworkInfo) ProtoReflect() protoreflect.Message {
	mi := &file_proto_homework_homework_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HomeworkInfo.ProtoReflect.Descriptor instead.
func (*HomeworkInfo) Descriptor() ([]byte, []int) {
	return file_proto_homework_homework_proto_rawDescGZIP(), []int{2}
}

func (x *HomeworkInfo) GetHomeworkID() int32 {
	if x != nil {
		return x.HomeworkID
	}
	return 0
}

func (x *HomeworkInfo) GetCourseID() int32 {
	if x != nil {
		return x.CourseID
	}
	return 0
}

func (x *HomeworkInfo) GetUserID() int32 {
	if x != nil {
		return x.UserID
	}
	return 0
}

func (x *HomeworkInfo) GetStartTime() int64 {
	if x != nil {
		return x.StartTime
	}
	return 0
}

func (x *HomeworkInfo) GetEndTime() int64 {
	if x != nil {
		return x.EndTime
	}
	return 0
}

func (x *HomeworkInfo) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *HomeworkInfo) GetState() int32 {
	if x != nil {
		return x.State
	}
	return 0
}

func (x *HomeworkInfo) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *HomeworkInfo) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

type UserID struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserID int32 `protobuf:"varint,1,opt,name=userID,proto3" json:"userID,omitempty"`
}

func (x *UserID) Reset() {
	*x = UserID{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_homework_homework_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UserID) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserID) ProtoMessage() {}

func (x *UserID) ProtoReflect() protoreflect.Message {
	mi := &file_proto_homework_homework_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserID.ProtoReflect.Descriptor instead.
func (*UserID) Descriptor() ([]byte, []int) {
	return file_proto_homework_homework_proto_rawDescGZIP(), []int{3}
}

func (x *UserID) GetUserID() int32 {
	if x != nil {
		return x.UserID
	}
	return 0
}

type AssignHomeworkResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status     AssignHomeworkResponse_Status `protobuf:"varint,1,opt,name=status,proto3,enum=go.micro.service.homework.AssignHomeworkResponse_Status" json:"status,omitempty"`
	Msg        string                        `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	HomeworkID int32                         `protobuf:"varint,3,opt,name=HomeworkID,proto3" json:"HomeworkID,omitempty"`
}

func (x *AssignHomeworkResponse) Reset() {
	*x = AssignHomeworkResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_homework_homework_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AssignHomeworkResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AssignHomeworkResponse) ProtoMessage() {}

func (x *AssignHomeworkResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_homework_homework_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AssignHomeworkResponse.ProtoReflect.Descriptor instead.
func (*AssignHomeworkResponse) Descriptor() ([]byte, []int) {
	return file_proto_homework_homework_proto_rawDescGZIP(), []int{4}
}

func (x *AssignHomeworkResponse) GetStatus() AssignHomeworkResponse_Status {
	if x != nil {
		return x.Status
	}
	return AssignHomeworkResponse_SUCCESS
}

func (x *AssignHomeworkResponse) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

func (x *AssignHomeworkResponse) GetHomeworkID() int32 {
	if x != nil {
		return x.HomeworkID
	}
	return 0
}

type DeleteHomeworkResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status DeleteHomeworkResponse_Status `protobuf:"varint,1,opt,name=status,proto3,enum=go.micro.service.homework.DeleteHomeworkResponse_Status" json:"status,omitempty"`
	Msg    string                        `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
}

func (x *DeleteHomeworkResponse) Reset() {
	*x = DeleteHomeworkResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_homework_homework_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteHomeworkResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteHomeworkResponse) ProtoMessage() {}

func (x *DeleteHomeworkResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_homework_homework_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteHomeworkResponse.ProtoReflect.Descriptor instead.
func (*DeleteHomeworkResponse) Descriptor() ([]byte, []int) {
	return file_proto_homework_homework_proto_rawDescGZIP(), []int{5}
}

func (x *DeleteHomeworkResponse) GetStatus() DeleteHomeworkResponse_Status {
	if x != nil {
		return x.Status
	}
	return DeleteHomeworkResponse_SUCCESS
}

func (x *DeleteHomeworkResponse) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

type UpdateHomeworkResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status UpdateHomeworkResponse_Status `protobuf:"varint,1,opt,name=status,proto3,enum=go.micro.service.homework.UpdateHomeworkResponse_Status" json:"status,omitempty"`
	Msg    string                        `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
}

func (x *UpdateHomeworkResponse) Reset() {
	*x = UpdateHomeworkResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_homework_homework_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateHomeworkResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateHomeworkResponse) ProtoMessage() {}

func (x *UpdateHomeworkResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_homework_homework_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateHomeworkResponse.ProtoReflect.Descriptor instead.
func (*UpdateHomeworkResponse) Descriptor() ([]byte, []int) {
	return file_proto_homework_homework_proto_rawDescGZIP(), []int{6}
}

func (x *UpdateHomeworkResponse) GetStatus() UpdateHomeworkResponse_Status {
	if x != nil {
		return x.Status
	}
	return UpdateHomeworkResponse_SUCCESS
}

func (x *UpdateHomeworkResponse) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

type SearchHomeworkResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status   SearchHomeworkResponse_Status `protobuf:"varint,1,opt,name=status,proto3,enum=go.micro.service.homework.SearchHomeworkResponse_Status" json:"status,omitempty"`
	Msg      string                        `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	Homework *HomeworkInfo                 `protobuf:"bytes,3,opt,name=homework,proto3" json:"homework,omitempty"`
}

func (x *SearchHomeworkResponse) Reset() {
	*x = SearchHomeworkResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_homework_homework_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SearchHomeworkResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchHomeworkResponse) ProtoMessage() {}

func (x *SearchHomeworkResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_homework_homework_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchHomeworkResponse.ProtoReflect.Descriptor instead.
func (*SearchHomeworkResponse) Descriptor() ([]byte, []int) {
	return file_proto_homework_homework_proto_rawDescGZIP(), []int{7}
}

func (x *SearchHomeworkResponse) GetStatus() SearchHomeworkResponse_Status {
	if x != nil {
		return x.Status
	}
	return SearchHomeworkResponse_SUCCESS
}

func (x *SearchHomeworkResponse) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

func (x *SearchHomeworkResponse) GetHomework() *HomeworkInfo {
	if x != nil {
		return x.Homework
	}
	return nil
}

type SearchHomeworkByUserIDResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status    SearchHomeworkByUserIDResponse_Status `protobuf:"varint,1,opt,name=status,proto3,enum=go.micro.service.homework.SearchHomeworkByUserIDResponse_Status" json:"status,omitempty"`
	Msg       string                                `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	Homeworks []*HomeworkInfo                       `protobuf:"bytes,3,rep,name=homeworks,proto3" json:"homeworks,omitempty"`
}

func (x *SearchHomeworkByUserIDResponse) Reset() {
	*x = SearchHomeworkByUserIDResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_homework_homework_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SearchHomeworkByUserIDResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchHomeworkByUserIDResponse) ProtoMessage() {}

func (x *SearchHomeworkByUserIDResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_homework_homework_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchHomeworkByUserIDResponse.ProtoReflect.Descriptor instead.
func (*SearchHomeworkByUserIDResponse) Descriptor() ([]byte, []int) {
	return file_proto_homework_homework_proto_rawDescGZIP(), []int{8}
}

func (x *SearchHomeworkByUserIDResponse) GetStatus() SearchHomeworkByUserIDResponse_Status {
	if x != nil {
		return x.Status
	}
	return SearchHomeworkByUserIDResponse_SUCCESS
}

func (x *SearchHomeworkByUserIDResponse) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

func (x *SearchHomeworkByUserIDResponse) GetHomeworks() []*HomeworkInfo {
	if x != nil {
		return x.Homeworks
	}
	return nil
}

var File_proto_homework_homework_proto protoreflect.FileDescriptor

var file_proto_homework_homework_proto_rawDesc = []byte{
	0x0a, 0x1d, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x68, 0x6f, 0x6d, 0x65, 0x77, 0x6f, 0x72, 0x6b,
	0x2f, 0x68, 0x6f, 0x6d, 0x65, 0x77, 0x6f, 0x72, 0x6b, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12,
	0x19, 0x67, 0x6f, 0x2e, 0x6d, 0x69, 0x63, 0x72, 0x6f, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63,
	0x65, 0x2e, 0x68, 0x6f, 0x6d, 0x65, 0x77, 0x6f, 0x72, 0x6b, 0x22, 0xe9, 0x01, 0x0a, 0x13, 0x41,
	0x73, 0x73, 0x69, 0x67, 0x6e, 0x48, 0x6f, 0x6d, 0x65, 0x77, 0x6f, 0x72, 0x6b, 0x50, 0x61, 0x72,
	0x61, 0x6d, 0x12, 0x1a, 0x0a, 0x08, 0x63, 0x6f, 0x75, 0x72, 0x73, 0x65, 0x49, 0x44, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x08, 0x63, 0x6f, 0x75, 0x72, 0x73, 0x65, 0x49, 0x44, 0x12, 0x16,
	0x0a, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x44, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06,
	0x75, 0x73, 0x65, 0x72, 0x49, 0x44, 0x12, 0x1c, 0x0a, 0x09, 0x73, 0x74, 0x61, 0x72, 0x74, 0x54,
	0x69, 0x6d, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x09, 0x73, 0x74, 0x61, 0x72, 0x74,
	0x54, 0x69, 0x6d, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x65, 0x6e, 0x64, 0x54, 0x69, 0x6d, 0x65, 0x18,
	0x04, 0x20, 0x01, 0x28, 0x03, 0x52, 0x07, 0x65, 0x6e, 0x64, 0x54, 0x69, 0x6d, 0x65, 0x12, 0x14,
	0x0a, 0x05, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x74,
	0x69, 0x74, 0x6c, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x73, 0x74, 0x61, 0x74, 0x65, 0x18, 0x06, 0x20,
	0x01, 0x28, 0x05, 0x52, 0x05, 0x73, 0x74, 0x61, 0x74, 0x65, 0x12, 0x20, 0x0a, 0x0b, 0x64, 0x65,
	0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x07, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x18, 0x0a, 0x07,
	0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x18, 0x08, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x63,
	0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x22, 0x2c, 0x0a, 0x0a, 0x48, 0x6f, 0x6d, 0x65, 0x77, 0x6f,
	0x72, 0x6b, 0x49, 0x44, 0x12, 0x1e, 0x0a, 0x0a, 0x68, 0x6f, 0x6d, 0x65, 0x77, 0x6f, 0x72, 0x6b,
	0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0a, 0x68, 0x6f, 0x6d, 0x65, 0x77, 0x6f,
	0x72, 0x6b, 0x49, 0x44, 0x22, 0x82, 0x02, 0x0a, 0x0c, 0x48, 0x6f, 0x6d, 0x65, 0x77, 0x6f, 0x72,
	0x6b, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x1e, 0x0a, 0x0a, 0x68, 0x6f, 0x6d, 0x65, 0x77, 0x6f, 0x72,
	0x6b, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0a, 0x68, 0x6f, 0x6d, 0x65, 0x77,
	0x6f, 0x72, 0x6b, 0x49, 0x44, 0x12, 0x1a, 0x0a, 0x08, 0x63, 0x6f, 0x75, 0x72, 0x73, 0x65, 0x49,
	0x44, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x08, 0x63, 0x6f, 0x75, 0x72, 0x73, 0x65, 0x49,
	0x44, 0x12, 0x16, 0x0a, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x44, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x44, 0x12, 0x1c, 0x0a, 0x09, 0x73, 0x74, 0x61,
	0x72, 0x74, 0x54, 0x69, 0x6d, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x03, 0x52, 0x09, 0x73, 0x74,
	0x61, 0x72, 0x74, 0x54, 0x69, 0x6d, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x65, 0x6e, 0x64, 0x54, 0x69,
	0x6d, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x03, 0x52, 0x07, 0x65, 0x6e, 0x64, 0x54, 0x69, 0x6d,
	0x65, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x05, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x73, 0x74, 0x61, 0x74, 0x65,
	0x18, 0x07, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x73, 0x74, 0x61, 0x74, 0x65, 0x12, 0x20, 0x0a,
	0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x08, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x12,
	0x18, 0x0a, 0x07, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x18, 0x09, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x07, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x22, 0x20, 0x0a, 0x06, 0x55, 0x73, 0x65,
	0x72, 0x49, 0x44, 0x12, 0x16, 0x0a, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x44, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x05, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x44, 0x22, 0xc7, 0x01, 0x0a, 0x16,
	0x41, 0x73, 0x73, 0x69, 0x67, 0x6e, 0x48, 0x6f, 0x6d, 0x65, 0x77, 0x6f, 0x72, 0x6b, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x50, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x38, 0x2e, 0x67, 0x6f, 0x2e, 0x6d, 0x69, 0x63, 0x72,
	0x6f, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x68, 0x6f, 0x6d, 0x65, 0x77, 0x6f,
	0x72, 0x6b, 0x2e, 0x41, 0x73, 0x73, 0x69, 0x67, 0x6e, 0x48, 0x6f, 0x6d, 0x65, 0x77, 0x6f, 0x72,
	0x6b, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x2e, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73,
	0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x10, 0x0a, 0x03, 0x6d, 0x73, 0x67, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6d, 0x73, 0x67, 0x12, 0x1e, 0x0a, 0x0a, 0x48, 0x6f,
	0x6d, 0x65, 0x77, 0x6f, 0x72, 0x6b, 0x49, 0x44, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0a,
	0x48, 0x6f, 0x6d, 0x65, 0x77, 0x6f, 0x72, 0x6b, 0x49, 0x44, 0x22, 0x29, 0x0a, 0x06, 0x53, 0x74,
	0x61, 0x74, 0x75, 0x73, 0x12, 0x0b, 0x0a, 0x07, 0x53, 0x55, 0x43, 0x43, 0x45, 0x53, 0x53, 0x10,
	0x00, 0x12, 0x12, 0x0a, 0x05, 0x45, 0x52, 0x52, 0x4f, 0x52, 0x10, 0xff, 0xff, 0xff, 0xff, 0xff,
	0xff, 0xff, 0xff, 0xff, 0x01, 0x22, 0xa7, 0x01, 0x0a, 0x16, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65,
	0x48, 0x6f, 0x6d, 0x65, 0x77, 0x6f, 0x72, 0x6b, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x12, 0x50, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e,
	0x32, 0x38, 0x2e, 0x67, 0x6f, 0x2e, 0x6d, 0x69, 0x63, 0x72, 0x6f, 0x2e, 0x73, 0x65, 0x72, 0x76,
	0x69, 0x63, 0x65, 0x2e, 0x68, 0x6f, 0x6d, 0x65, 0x77, 0x6f, 0x72, 0x6b, 0x2e, 0x44, 0x65, 0x6c,
	0x65, 0x74, 0x65, 0x48, 0x6f, 0x6d, 0x65, 0x77, 0x6f, 0x72, 0x6b, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x2e, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74,
	0x75, 0x73, 0x12, 0x10, 0x0a, 0x03, 0x6d, 0x73, 0x67, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x03, 0x6d, 0x73, 0x67, 0x22, 0x29, 0x0a, 0x06, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x0b,
	0x0a, 0x07, 0x53, 0x55, 0x43, 0x43, 0x45, 0x53, 0x53, 0x10, 0x00, 0x12, 0x12, 0x0a, 0x05, 0x45,
	0x52, 0x52, 0x4f, 0x52, 0x10, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0x01, 0x22,
	0xa7, 0x01, 0x0a, 0x16, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x48, 0x6f, 0x6d, 0x65, 0x77, 0x6f,
	0x72, 0x6b, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x50, 0x0a, 0x06, 0x73, 0x74,
	0x61, 0x74, 0x75, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x38, 0x2e, 0x67, 0x6f, 0x2e,
	0x6d, 0x69, 0x63, 0x72, 0x6f, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x68, 0x6f,
	0x6d, 0x65, 0x77, 0x6f, 0x72, 0x6b, 0x2e, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x48, 0x6f, 0x6d,
	0x65, 0x77, 0x6f, 0x72, 0x6b, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x2e, 0x53, 0x74,
	0x61, 0x74, 0x75, 0x73, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x10, 0x0a, 0x03,
	0x6d, 0x73, 0x67, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6d, 0x73, 0x67, 0x22, 0x29,
	0x0a, 0x06, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x0b, 0x0a, 0x07, 0x53, 0x55, 0x43, 0x43,
	0x45, 0x53, 0x53, 0x10, 0x00, 0x12, 0x12, 0x0a, 0x05, 0x45, 0x52, 0x52, 0x4f, 0x52, 0x10, 0xff,
	0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0x01, 0x22, 0xec, 0x01, 0x0a, 0x16, 0x53, 0x65,
	0x61, 0x72, 0x63, 0x68, 0x48, 0x6f, 0x6d, 0x65, 0x77, 0x6f, 0x72, 0x6b, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x12, 0x50, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0e, 0x32, 0x38, 0x2e, 0x67, 0x6f, 0x2e, 0x6d, 0x69, 0x63, 0x72, 0x6f, 0x2e,
	0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x68, 0x6f, 0x6d, 0x65, 0x77, 0x6f, 0x72, 0x6b,
	0x2e, 0x53, 0x65, 0x61, 0x72, 0x63, 0x68, 0x48, 0x6f, 0x6d, 0x65, 0x77, 0x6f, 0x72, 0x6b, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x2e, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x06,
	0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x10, 0x0a, 0x03, 0x6d, 0x73, 0x67, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x03, 0x6d, 0x73, 0x67, 0x12, 0x43, 0x0a, 0x08, 0x68, 0x6f, 0x6d, 0x65,
	0x77, 0x6f, 0x72, 0x6b, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x27, 0x2e, 0x67, 0x6f, 0x2e,
	0x6d, 0x69, 0x63, 0x72, 0x6f, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x68, 0x6f,
	0x6d, 0x65, 0x77, 0x6f, 0x72, 0x6b, 0x2e, 0x48, 0x6f, 0x6d, 0x65, 0x77, 0x6f, 0x72, 0x6b, 0x49,
	0x6e, 0x66, 0x6f, 0x52, 0x08, 0x68, 0x6f, 0x6d, 0x65, 0x77, 0x6f, 0x72, 0x6b, 0x22, 0x29, 0x0a,
	0x06, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x0b, 0x0a, 0x07, 0x53, 0x55, 0x43, 0x43, 0x45,
	0x53, 0x53, 0x10, 0x00, 0x12, 0x12, 0x0a, 0x05, 0x45, 0x52, 0x52, 0x4f, 0x52, 0x10, 0xff, 0xff,
	0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0x01, 0x22, 0xfe, 0x01, 0x0a, 0x1e, 0x53, 0x65, 0x61,
	0x72, 0x63, 0x68, 0x48, 0x6f, 0x6d, 0x65, 0x77, 0x6f, 0x72, 0x6b, 0x42, 0x79, 0x55, 0x73, 0x65,
	0x72, 0x49, 0x44, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x58, 0x0a, 0x06, 0x73,
	0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x40, 0x2e, 0x67, 0x6f,
	0x2e, 0x6d, 0x69, 0x63, 0x72, 0x6f, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x68,
	0x6f, 0x6d, 0x65, 0x77, 0x6f, 0x72, 0x6b, 0x2e, 0x53, 0x65, 0x61, 0x72, 0x63, 0x68, 0x48, 0x6f,
	0x6d, 0x65, 0x77, 0x6f, 0x72, 0x6b, 0x42, 0x79, 0x55, 0x73, 0x65, 0x72, 0x49, 0x44, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x2e, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x06, 0x73,
	0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x10, 0x0a, 0x03, 0x6d, 0x73, 0x67, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x03, 0x6d, 0x73, 0x67, 0x12, 0x45, 0x0a, 0x09, 0x68, 0x6f, 0x6d, 0x65, 0x77,
	0x6f, 0x72, 0x6b, 0x73, 0x18, 0x03, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x27, 0x2e, 0x67, 0x6f, 0x2e,
	0x6d, 0x69, 0x63, 0x72, 0x6f, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x68, 0x6f,
	0x6d, 0x65, 0x77, 0x6f, 0x72, 0x6b, 0x2e, 0x48, 0x6f, 0x6d, 0x65, 0x77, 0x6f, 0x72, 0x6b, 0x49,
	0x6e, 0x66, 0x6f, 0x52, 0x09, 0x68, 0x6f, 0x6d, 0x65, 0x77, 0x6f, 0x72, 0x6b, 0x73, 0x22, 0x29,
	0x0a, 0x06, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x0b, 0x0a, 0x07, 0x53, 0x55, 0x43, 0x43,
	0x45, 0x53, 0x53, 0x10, 0x00, 0x12, 0x12, 0x0a, 0x05, 0x45, 0x52, 0x52, 0x4f, 0x52, 0x10, 0xff,
	0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0x01, 0x32, 0xce, 0x04, 0x0a, 0x0f, 0x48, 0x6f,
	0x6d, 0x65, 0x77, 0x6f, 0x72, 0x6b, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x75, 0x0a,
	0x0e, 0x41, 0x73, 0x73, 0x69, 0x67, 0x6e, 0x48, 0x6f, 0x6d, 0x65, 0x77, 0x6f, 0x72, 0x6b, 0x12,
	0x2e, 0x2e, 0x67, 0x6f, 0x2e, 0x6d, 0x69, 0x63, 0x72, 0x6f, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x69,
	0x63, 0x65, 0x2e, 0x68, 0x6f, 0x6d, 0x65, 0x77, 0x6f, 0x72, 0x6b, 0x2e, 0x41, 0x73, 0x73, 0x69,
	0x67, 0x6e, 0x48, 0x6f, 0x6d, 0x65, 0x77, 0x6f, 0x72, 0x6b, 0x50, 0x61, 0x72, 0x61, 0x6d, 0x1a,
	0x31, 0x2e, 0x67, 0x6f, 0x2e, 0x6d, 0x69, 0x63, 0x72, 0x6f, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x69,
	0x63, 0x65, 0x2e, 0x68, 0x6f, 0x6d, 0x65, 0x77, 0x6f, 0x72, 0x6b, 0x2e, 0x41, 0x73, 0x73, 0x69,
	0x67, 0x6e, 0x48, 0x6f, 0x6d, 0x65, 0x77, 0x6f, 0x72, 0x6b, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x22, 0x00, 0x12, 0x6c, 0x0a, 0x0e, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x48, 0x6f,
	0x6d, 0x65, 0x77, 0x6f, 0x72, 0x6b, 0x12, 0x25, 0x2e, 0x67, 0x6f, 0x2e, 0x6d, 0x69, 0x63, 0x72,
	0x6f, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x68, 0x6f, 0x6d, 0x65, 0x77, 0x6f,
	0x72, 0x6b, 0x2e, 0x48, 0x6f, 0x6d, 0x65, 0x77, 0x6f, 0x72, 0x6b, 0x49, 0x44, 0x1a, 0x31, 0x2e,
	0x67, 0x6f, 0x2e, 0x6d, 0x69, 0x63, 0x72, 0x6f, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65,
	0x2e, 0x68, 0x6f, 0x6d, 0x65, 0x77, 0x6f, 0x72, 0x6b, 0x2e, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65,
	0x48, 0x6f, 0x6d, 0x65, 0x77, 0x6f, 0x72, 0x6b, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x22, 0x00, 0x12, 0x6e, 0x0a, 0x0e, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x48, 0x6f, 0x6d, 0x65,
	0x77, 0x6f, 0x72, 0x6b, 0x12, 0x27, 0x2e, 0x67, 0x6f, 0x2e, 0x6d, 0x69, 0x63, 0x72, 0x6f, 0x2e,
	0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x68, 0x6f, 0x6d, 0x65, 0x77, 0x6f, 0x72, 0x6b,
	0x2e, 0x48, 0x6f, 0x6d, 0x65, 0x77, 0x6f, 0x72, 0x6b, 0x49, 0x6e, 0x66, 0x6f, 0x1a, 0x31, 0x2e,
	0x67, 0x6f, 0x2e, 0x6d, 0x69, 0x63, 0x72, 0x6f, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65,
	0x2e, 0x68, 0x6f, 0x6d, 0x65, 0x77, 0x6f, 0x72, 0x6b, 0x2e, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65,
	0x48, 0x6f, 0x6d, 0x65, 0x77, 0x6f, 0x72, 0x6b, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x22, 0x00, 0x12, 0x6c, 0x0a, 0x0e, 0x53, 0x65, 0x61, 0x72, 0x63, 0x68, 0x48, 0x6f, 0x6d, 0x65,
	0x77, 0x6f, 0x72, 0x6b, 0x12, 0x25, 0x2e, 0x67, 0x6f, 0x2e, 0x6d, 0x69, 0x63, 0x72, 0x6f, 0x2e,
	0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x68, 0x6f, 0x6d, 0x65, 0x77, 0x6f, 0x72, 0x6b,
	0x2e, 0x48, 0x6f, 0x6d, 0x65, 0x77, 0x6f, 0x72, 0x6b, 0x49, 0x44, 0x1a, 0x31, 0x2e, 0x67, 0x6f,
	0x2e, 0x6d, 0x69, 0x63, 0x72, 0x6f, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x68,
	0x6f, 0x6d, 0x65, 0x77, 0x6f, 0x72, 0x6b, 0x2e, 0x53, 0x65, 0x61, 0x72, 0x63, 0x68, 0x48, 0x6f,
	0x6d, 0x65, 0x77, 0x6f, 0x72, 0x6b, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00,
	0x12, 0x78, 0x0a, 0x16, 0x53, 0x65, 0x61, 0x72, 0x63, 0x68, 0x48, 0x6f, 0x6d, 0x65, 0x77, 0x6f,
	0x72, 0x6b, 0x42, 0x79, 0x55, 0x73, 0x65, 0x72, 0x49, 0x44, 0x12, 0x21, 0x2e, 0x67, 0x6f, 0x2e,
	0x6d, 0x69, 0x63, 0x72, 0x6f, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x68, 0x6f,
	0x6d, 0x65, 0x77, 0x6f, 0x72, 0x6b, 0x2e, 0x55, 0x73, 0x65, 0x72, 0x49, 0x44, 0x1a, 0x39, 0x2e,
	0x67, 0x6f, 0x2e, 0x6d, 0x69, 0x63, 0x72, 0x6f, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65,
	0x2e, 0x68, 0x6f, 0x6d, 0x65, 0x77, 0x6f, 0x72, 0x6b, 0x2e, 0x53, 0x65, 0x61, 0x72, 0x63, 0x68,
	0x48, 0x6f, 0x6d, 0x65, 0x77, 0x6f, 0x72, 0x6b, 0x42, 0x79, 0x55, 0x73, 0x65, 0x72, 0x49, 0x44,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x42, 0x10, 0x5a, 0x0e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x2f, 0x68, 0x6f, 0x6d, 0x65, 0x77, 0x6f, 0x72, 0x6b, 0x62, 0x06, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_proto_homework_homework_proto_rawDescOnce sync.Once
	file_proto_homework_homework_proto_rawDescData = file_proto_homework_homework_proto_rawDesc
)

func file_proto_homework_homework_proto_rawDescGZIP() []byte {
	file_proto_homework_homework_proto_rawDescOnce.Do(func() {
		file_proto_homework_homework_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_homework_homework_proto_rawDescData)
	})
	return file_proto_homework_homework_proto_rawDescData
}

var file_proto_homework_homework_proto_enumTypes = make([]protoimpl.EnumInfo, 5)
var file_proto_homework_homework_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_proto_homework_homework_proto_goTypes = []interface{}{
	(AssignHomeworkResponse_Status)(0),         // 0: go.micro.service.homework.AssignHomeworkResponse.Status
	(DeleteHomeworkResponse_Status)(0),         // 1: go.micro.service.homework.DeleteHomeworkResponse.Status
	(UpdateHomeworkResponse_Status)(0),         // 2: go.micro.service.homework.UpdateHomeworkResponse.Status
	(SearchHomeworkResponse_Status)(0),         // 3: go.micro.service.homework.SearchHomeworkResponse.Status
	(SearchHomeworkByUserIDResponse_Status)(0), // 4: go.micro.service.homework.SearchHomeworkByUserIDResponse.Status
	(*AssignHomeworkParam)(nil),                // 5: go.micro.service.homework.AssignHomeworkParam
	(*HomeworkID)(nil),                         // 6: go.micro.service.homework.HomeworkID
	(*HomeworkInfo)(nil),                       // 7: go.micro.service.homework.HomeworkInfo
	(*UserID)(nil),                             // 8: go.micro.service.homework.UserID
	(*AssignHomeworkResponse)(nil),             // 9: go.micro.service.homework.AssignHomeworkResponse
	(*DeleteHomeworkResponse)(nil),             // 10: go.micro.service.homework.DeleteHomeworkResponse
	(*UpdateHomeworkResponse)(nil),             // 11: go.micro.service.homework.UpdateHomeworkResponse
	(*SearchHomeworkResponse)(nil),             // 12: go.micro.service.homework.SearchHomeworkResponse
	(*SearchHomeworkByUserIDResponse)(nil),     // 13: go.micro.service.homework.SearchHomeworkByUserIDResponse
}
var file_proto_homework_homework_proto_depIdxs = []int32{
	0,  // 0: go.micro.service.homework.AssignHomeworkResponse.status:type_name -> go.micro.service.homework.AssignHomeworkResponse.Status
	1,  // 1: go.micro.service.homework.DeleteHomeworkResponse.status:type_name -> go.micro.service.homework.DeleteHomeworkResponse.Status
	2,  // 2: go.micro.service.homework.UpdateHomeworkResponse.status:type_name -> go.micro.service.homework.UpdateHomeworkResponse.Status
	3,  // 3: go.micro.service.homework.SearchHomeworkResponse.status:type_name -> go.micro.service.homework.SearchHomeworkResponse.Status
	7,  // 4: go.micro.service.homework.SearchHomeworkResponse.homework:type_name -> go.micro.service.homework.HomeworkInfo
	4,  // 5: go.micro.service.homework.SearchHomeworkByUserIDResponse.status:type_name -> go.micro.service.homework.SearchHomeworkByUserIDResponse.Status
	7,  // 6: go.micro.service.homework.SearchHomeworkByUserIDResponse.homeworks:type_name -> go.micro.service.homework.HomeworkInfo
	5,  // 7: go.micro.service.homework.HomeworkService.AssignHomework:input_type -> go.micro.service.homework.AssignHomeworkParam
	6,  // 8: go.micro.service.homework.HomeworkService.DeleteHomework:input_type -> go.micro.service.homework.HomeworkID
	7,  // 9: go.micro.service.homework.HomeworkService.UpdateHomework:input_type -> go.micro.service.homework.HomeworkInfo
	6,  // 10: go.micro.service.homework.HomeworkService.SearchHomework:input_type -> go.micro.service.homework.HomeworkID
	8,  // 11: go.micro.service.homework.HomeworkService.SearchHomeworkByUserID:input_type -> go.micro.service.homework.UserID
	9,  // 12: go.micro.service.homework.HomeworkService.AssignHomework:output_type -> go.micro.service.homework.AssignHomeworkResponse
	10, // 13: go.micro.service.homework.HomeworkService.DeleteHomework:output_type -> go.micro.service.homework.DeleteHomeworkResponse
	11, // 14: go.micro.service.homework.HomeworkService.UpdateHomework:output_type -> go.micro.service.homework.UpdateHomeworkResponse
	12, // 15: go.micro.service.homework.HomeworkService.SearchHomework:output_type -> go.micro.service.homework.SearchHomeworkResponse
	13, // 16: go.micro.service.homework.HomeworkService.SearchHomeworkByUserID:output_type -> go.micro.service.homework.SearchHomeworkByUserIDResponse
	12, // [12:17] is the sub-list for method output_type
	7,  // [7:12] is the sub-list for method input_type
	7,  // [7:7] is the sub-list for extension type_name
	7,  // [7:7] is the sub-list for extension extendee
	0,  // [0:7] is the sub-list for field type_name
}

func init() { file_proto_homework_homework_proto_init() }
func file_proto_homework_homework_proto_init() {
	if File_proto_homework_homework_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_proto_homework_homework_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AssignHomeworkParam); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_homework_homework_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*HomeworkID); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_homework_homework_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*HomeworkInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_homework_homework_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UserID); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_homework_homework_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AssignHomeworkResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_homework_homework_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteHomeworkResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_homework_homework_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateHomeworkResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_homework_homework_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SearchHomeworkResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_homework_homework_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SearchHomeworkByUserIDResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_homework_homework_proto_rawDesc,
			NumEnums:      5,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_homework_homework_proto_goTypes,
		DependencyIndexes: file_proto_homework_homework_proto_depIdxs,
		EnumInfos:         file_proto_homework_homework_proto_enumTypes,
		MessageInfos:      file_proto_homework_homework_proto_msgTypes,
	}.Build()
	File_proto_homework_homework_proto = out.File
	file_proto_homework_homework_proto_rawDesc = nil
	file_proto_homework_homework_proto_goTypes = nil
	file_proto_homework_homework_proto_depIdxs = nil
}
