//声明proto本版

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0
// 	protoc        v3.14.0
// source: proto/check/check.proto

//服务名

package check

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type CreateCheckResponse_Status int32

const (
	CreateCheckResponse_SUCCESS CreateCheckResponse_Status = 0
	CreateCheckResponse_ERROR   CreateCheckResponse_Status = -1
)

// Enum value maps for CreateCheckResponse_Status.
var (
	CreateCheckResponse_Status_name = map[int32]string{
		0:  "SUCCESS",
		-1: "ERROR",
	}
	CreateCheckResponse_Status_value = map[string]int32{
		"SUCCESS": 0,
		"ERROR":   -1,
	}
)

func (x CreateCheckResponse_Status) Enum() *CreateCheckResponse_Status {
	p := new(CreateCheckResponse_Status)
	*p = x
	return p
}

func (x CreateCheckResponse_Status) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (CreateCheckResponse_Status) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_check_check_proto_enumTypes[0].Descriptor()
}

func (CreateCheckResponse_Status) Type() protoreflect.EnumType {
	return &file_proto_check_check_proto_enumTypes[0]
}

func (x CreateCheckResponse_Status) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use CreateCheckResponse_Status.Descriptor instead.
func (CreateCheckResponse_Status) EnumDescriptor() ([]byte, []int) {
	return file_proto_check_check_proto_rawDescGZIP(), []int{5, 0}
}

type DeleteCheckResponse_Status int32

const (
	DeleteCheckResponse_SUCCESS DeleteCheckResponse_Status = 0
	DeleteCheckResponse_ERROR   DeleteCheckResponse_Status = -1
)

// Enum value maps for DeleteCheckResponse_Status.
var (
	DeleteCheckResponse_Status_name = map[int32]string{
		0:  "SUCCESS",
		-1: "ERROR",
	}
	DeleteCheckResponse_Status_value = map[string]int32{
		"SUCCESS": 0,
		"ERROR":   -1,
	}
)

func (x DeleteCheckResponse_Status) Enum() *DeleteCheckResponse_Status {
	p := new(DeleteCheckResponse_Status)
	*p = x
	return p
}

func (x DeleteCheckResponse_Status) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (DeleteCheckResponse_Status) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_check_check_proto_enumTypes[1].Descriptor()
}

func (DeleteCheckResponse_Status) Type() protoreflect.EnumType {
	return &file_proto_check_check_proto_enumTypes[1]
}

func (x DeleteCheckResponse_Status) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use DeleteCheckResponse_Status.Descriptor instead.
func (DeleteCheckResponse_Status) EnumDescriptor() ([]byte, []int) {
	return file_proto_check_check_proto_rawDescGZIP(), []int{6, 0}
}

type UpdateCheckResponse_Status int32

const (
	UpdateCheckResponse_SUCCESS UpdateCheckResponse_Status = 0
	UpdateCheckResponse_ERROR   UpdateCheckResponse_Status = -1
)

// Enum value maps for UpdateCheckResponse_Status.
var (
	UpdateCheckResponse_Status_name = map[int32]string{
		0:  "SUCCESS",
		-1: "ERROR",
	}
	UpdateCheckResponse_Status_value = map[string]int32{
		"SUCCESS": 0,
		"ERROR":   -1,
	}
)

func (x UpdateCheckResponse_Status) Enum() *UpdateCheckResponse_Status {
	p := new(UpdateCheckResponse_Status)
	*p = x
	return p
}

func (x UpdateCheckResponse_Status) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (UpdateCheckResponse_Status) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_check_check_proto_enumTypes[2].Descriptor()
}

func (UpdateCheckResponse_Status) Type() protoreflect.EnumType {
	return &file_proto_check_check_proto_enumTypes[2]
}

func (x UpdateCheckResponse_Status) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use UpdateCheckResponse_Status.Descriptor instead.
func (UpdateCheckResponse_Status) EnumDescriptor() ([]byte, []int) {
	return file_proto_check_check_proto_rawDescGZIP(), []int{7, 0}
}

type SearchCheckResponse_Status int32

const (
	SearchCheckResponse_SUCCESS SearchCheckResponse_Status = 0
	SearchCheckResponse_ERROR   SearchCheckResponse_Status = -1
)

// Enum value maps for SearchCheckResponse_Status.
var (
	SearchCheckResponse_Status_name = map[int32]string{
		0:  "SUCCESS",
		-1: "ERROR",
	}
	SearchCheckResponse_Status_value = map[string]int32{
		"SUCCESS": 0,
		"ERROR":   -1,
	}
)

func (x SearchCheckResponse_Status) Enum() *SearchCheckResponse_Status {
	p := new(SearchCheckResponse_Status)
	*p = x
	return p
}

func (x SearchCheckResponse_Status) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SearchCheckResponse_Status) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_check_check_proto_enumTypes[3].Descriptor()
}

func (SearchCheckResponse_Status) Type() protoreflect.EnumType {
	return &file_proto_check_check_proto_enumTypes[3]
}

func (x SearchCheckResponse_Status) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SearchCheckResponse_Status.Descriptor instead.
func (SearchCheckResponse_Status) EnumDescriptor() ([]byte, []int) {
	return file_proto_check_check_proto_rawDescGZIP(), []int{8, 0}
}

type SearchCheckByTeacherIDResponse_Status int32

const (
	SearchCheckByTeacherIDResponse_SUCCESS SearchCheckByTeacherIDResponse_Status = 0
	SearchCheckByTeacherIDResponse_ERROR   SearchCheckByTeacherIDResponse_Status = -1
)

// Enum value maps for SearchCheckByTeacherIDResponse_Status.
var (
	SearchCheckByTeacherIDResponse_Status_name = map[int32]string{
		0:  "SUCCESS",
		-1: "ERROR",
	}
	SearchCheckByTeacherIDResponse_Status_value = map[string]int32{
		"SUCCESS": 0,
		"ERROR":   -1,
	}
)

func (x SearchCheckByTeacherIDResponse_Status) Enum() *SearchCheckByTeacherIDResponse_Status {
	p := new(SearchCheckByTeacherIDResponse_Status)
	*p = x
	return p
}

func (x SearchCheckByTeacherIDResponse_Status) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SearchCheckByTeacherIDResponse_Status) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_check_check_proto_enumTypes[4].Descriptor()
}

func (SearchCheckByTeacherIDResponse_Status) Type() protoreflect.EnumType {
	return &file_proto_check_check_proto_enumTypes[4]
}

func (x SearchCheckByTeacherIDResponse_Status) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SearchCheckByTeacherIDResponse_Status.Descriptor instead.
func (SearchCheckByTeacherIDResponse_Status) EnumDescriptor() ([]byte, []int) {
	return file_proto_check_check_proto_rawDescGZIP(), []int{9, 0}
}

type SearchCheckByHomeworkIDResponse_Status int32

const (
	SearchCheckByHomeworkIDResponse_SUCCESS SearchCheckByHomeworkIDResponse_Status = 0
	SearchCheckByHomeworkIDResponse_ERROR   SearchCheckByHomeworkIDResponse_Status = -1
)

// Enum value maps for SearchCheckByHomeworkIDResponse_Status.
var (
	SearchCheckByHomeworkIDResponse_Status_name = map[int32]string{
		0:  "SUCCESS",
		-1: "ERROR",
	}
	SearchCheckByHomeworkIDResponse_Status_value = map[string]int32{
		"SUCCESS": 0,
		"ERROR":   -1,
	}
)

func (x SearchCheckByHomeworkIDResponse_Status) Enum() *SearchCheckByHomeworkIDResponse_Status {
	p := new(SearchCheckByHomeworkIDResponse_Status)
	*p = x
	return p
}

func (x SearchCheckByHomeworkIDResponse_Status) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SearchCheckByHomeworkIDResponse_Status) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_check_check_proto_enumTypes[5].Descriptor()
}

func (SearchCheckByHomeworkIDResponse_Status) Type() protoreflect.EnumType {
	return &file_proto_check_check_proto_enumTypes[5]
}

func (x SearchCheckByHomeworkIDResponse_Status) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SearchCheckByHomeworkIDResponse_Status.Descriptor instead.
func (SearchCheckByHomeworkIDResponse_Status) EnumDescriptor() ([]byte, []int) {
	return file_proto_check_check_proto_rawDescGZIP(), []int{10, 0}
}

//Parameter protocol
type CreateCheckParam struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AnswerID   int32  `protobuf:"varint,1,opt,name=AnswerID,proto3" json:"AnswerID,omitempty"`
	HomeworkID int32  `protobuf:"varint,2,opt,name=homeworkID,proto3" json:"homeworkID,omitempty"`
	TeacherID  int32  `protobuf:"varint,3,opt,name=teacherID,proto3" json:"teacherID,omitempty"`
	CheckTime  int64  `protobuf:"varint,4,opt,name=checkTime,proto3" json:"checkTime,omitempty"`
	CheckJson  string `protobuf:"bytes,5,opt,name=check_json,json=checkJson,proto3" json:"check_json,omitempty"`
}

func (x *CreateCheckParam) Reset() {
	*x = CreateCheckParam{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_check_check_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateCheckParam) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateCheckParam) ProtoMessage() {}

func (x *CreateCheckParam) ProtoReflect() protoreflect.Message {
	mi := &file_proto_check_check_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateCheckParam.ProtoReflect.Descriptor instead.
func (*CreateCheckParam) Descriptor() ([]byte, []int) {
	return file_proto_check_check_proto_rawDescGZIP(), []int{0}
}

func (x *CreateCheckParam) GetAnswerID() int32 {
	if x != nil {
		return x.AnswerID
	}
	return 0
}

func (x *CreateCheckParam) GetHomeworkID() int32 {
	if x != nil {
		return x.HomeworkID
	}
	return 0
}

func (x *CreateCheckParam) GetTeacherID() int32 {
	if x != nil {
		return x.TeacherID
	}
	return 0
}

func (x *CreateCheckParam) GetCheckTime() int64 {
	if x != nil {
		return x.CheckTime
	}
	return 0
}

func (x *CreateCheckParam) GetCheckJson() string {
	if x != nil {
		return x.CheckJson
	}
	return ""
}

type CheckID struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CheckID int32 `protobuf:"varint,1,opt,name=CheckID,proto3" json:"CheckID,omitempty"`
}

func (x *CheckID) Reset() {
	*x = CheckID{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_check_check_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CheckID) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckID) ProtoMessage() {}

func (x *CheckID) ProtoReflect() protoreflect.Message {
	mi := &file_proto_check_check_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckID.ProtoReflect.Descriptor instead.
func (*CheckID) Descriptor() ([]byte, []int) {
	return file_proto_check_check_proto_rawDescGZIP(), []int{1}
}

func (x *CheckID) GetCheckID() int32 {
	if x != nil {
		return x.CheckID
	}
	return 0
}

type CheckInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CheckID    int32  `protobuf:"varint,1,opt,name=CheckID,proto3" json:"CheckID,omitempty"`
	AnswerID   int32  `protobuf:"varint,2,opt,name=AnswerID,proto3" json:"AnswerID,omitempty"`
	HomeworkID int32  `protobuf:"varint,3,opt,name=homeworkID,proto3" json:"homeworkID,omitempty"`
	TeacherID  int32  `protobuf:"varint,4,opt,name=teacherID,proto3" json:"teacherID,omitempty"`
	CheckTime  int64  `protobuf:"varint,5,opt,name=checkTime,proto3" json:"checkTime,omitempty"`
	CheckJson  string `protobuf:"bytes,6,opt,name=check_json,json=checkJson,proto3" json:"check_json,omitempty"`
}

func (x *CheckInfo) Reset() {
	*x = CheckInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_check_check_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CheckInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckInfo) ProtoMessage() {}

func (x *CheckInfo) ProtoReflect() protoreflect.Message {
	mi := &file_proto_check_check_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckInfo.ProtoReflect.Descriptor instead.
func (*CheckInfo) Descriptor() ([]byte, []int) {
	return file_proto_check_check_proto_rawDescGZIP(), []int{2}
}

func (x *CheckInfo) GetCheckID() int32 {
	if x != nil {
		return x.CheckID
	}
	return 0
}

func (x *CheckInfo) GetAnswerID() int32 {
	if x != nil {
		return x.AnswerID
	}
	return 0
}

func (x *CheckInfo) GetHomeworkID() int32 {
	if x != nil {
		return x.HomeworkID
	}
	return 0
}

func (x *CheckInfo) GetTeacherID() int32 {
	if x != nil {
		return x.TeacherID
	}
	return 0
}

func (x *CheckInfo) GetCheckTime() int64 {
	if x != nil {
		return x.CheckTime
	}
	return 0
}

func (x *CheckInfo) GetCheckJson() string {
	if x != nil {
		return x.CheckJson
	}
	return ""
}

type TeacherID struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TeacherID int32 `protobuf:"varint,1,opt,name=TeacherID,proto3" json:"TeacherID,omitempty"`
}

func (x *TeacherID) Reset() {
	*x = TeacherID{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_check_check_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TeacherID) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TeacherID) ProtoMessage() {}

func (x *TeacherID) ProtoReflect() protoreflect.Message {
	mi := &file_proto_check_check_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TeacherID.ProtoReflect.Descriptor instead.
func (*TeacherID) Descriptor() ([]byte, []int) {
	return file_proto_check_check_proto_rawDescGZIP(), []int{3}
}

func (x *TeacherID) GetTeacherID() int32 {
	if x != nil {
		return x.TeacherID
	}
	return 0
}

type HomeworkID struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	HomeworkID int32 `protobuf:"varint,1,opt,name=HomeworkID,proto3" json:"HomeworkID,omitempty"`
}

func (x *HomeworkID) Reset() {
	*x = HomeworkID{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_check_check_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HomeworkID) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HomeworkID) ProtoMessage() {}

func (x *HomeworkID) ProtoReflect() protoreflect.Message {
	mi := &file_proto_check_check_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HomeworkID.ProtoReflect.Descriptor instead.
func (*HomeworkID) Descriptor() ([]byte, []int) {
	return file_proto_check_check_proto_rawDescGZIP(), []int{4}
}

func (x *HomeworkID) GetHomeworkID() int32 {
	if x != nil {
		return x.HomeworkID
	}
	return 0
}

type CreateCheckResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status  CreateCheckResponse_Status `protobuf:"varint,1,opt,name=status,proto3,enum=go.micro.service.check.CreateCheckResponse_Status" json:"status,omitempty"`
	Msg     string                     `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	CheckID int32                      `protobuf:"varint,3,opt,name=CheckID,proto3" json:"CheckID,omitempty"`
}

func (x *CreateCheckResponse) Reset() {
	*x = CreateCheckResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_check_check_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateCheckResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateCheckResponse) ProtoMessage() {}

func (x *CreateCheckResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_check_check_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateCheckResponse.ProtoReflect.Descriptor instead.
func (*CreateCheckResponse) Descriptor() ([]byte, []int) {
	return file_proto_check_check_proto_rawDescGZIP(), []int{5}
}

func (x *CreateCheckResponse) GetStatus() CreateCheckResponse_Status {
	if x != nil {
		return x.Status
	}
	return CreateCheckResponse_SUCCESS
}

func (x *CreateCheckResponse) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

func (x *CreateCheckResponse) GetCheckID() int32 {
	if x != nil {
		return x.CheckID
	}
	return 0
}

type DeleteCheckResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status DeleteCheckResponse_Status `protobuf:"varint,1,opt,name=status,proto3,enum=go.micro.service.check.DeleteCheckResponse_Status" json:"status,omitempty"`
	Msg    string                     `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
}

func (x *DeleteCheckResponse) Reset() {
	*x = DeleteCheckResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_check_check_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteCheckResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteCheckResponse) ProtoMessage() {}

func (x *DeleteCheckResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_check_check_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteCheckResponse.ProtoReflect.Descriptor instead.
func (*DeleteCheckResponse) Descriptor() ([]byte, []int) {
	return file_proto_check_check_proto_rawDescGZIP(), []int{6}
}

func (x *DeleteCheckResponse) GetStatus() DeleteCheckResponse_Status {
	if x != nil {
		return x.Status
	}
	return DeleteCheckResponse_SUCCESS
}

func (x *DeleteCheckResponse) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

type UpdateCheckResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status UpdateCheckResponse_Status `protobuf:"varint,1,opt,name=status,proto3,enum=go.micro.service.check.UpdateCheckResponse_Status" json:"status,omitempty"`
	Msg    string                     `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
}

func (x *UpdateCheckResponse) Reset() {
	*x = UpdateCheckResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_check_check_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateCheckResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateCheckResponse) ProtoMessage() {}

func (x *UpdateCheckResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_check_check_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateCheckResponse.ProtoReflect.Descriptor instead.
func (*UpdateCheckResponse) Descriptor() ([]byte, []int) {
	return file_proto_check_check_proto_rawDescGZIP(), []int{7}
}

func (x *UpdateCheckResponse) GetStatus() UpdateCheckResponse_Status {
	if x != nil {
		return x.Status
	}
	return UpdateCheckResponse_SUCCESS
}

func (x *UpdateCheckResponse) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

type SearchCheckResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status SearchCheckResponse_Status `protobuf:"varint,1,opt,name=status,proto3,enum=go.micro.service.check.SearchCheckResponse_Status" json:"status,omitempty"`
	Msg    string                     `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	Check  *CheckInfo                 `protobuf:"bytes,3,opt,name=check,proto3" json:"check,omitempty"`
}

func (x *SearchCheckResponse) Reset() {
	*x = SearchCheckResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_check_check_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SearchCheckResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchCheckResponse) ProtoMessage() {}

func (x *SearchCheckResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_check_check_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchCheckResponse.ProtoReflect.Descriptor instead.
func (*SearchCheckResponse) Descriptor() ([]byte, []int) {
	return file_proto_check_check_proto_rawDescGZIP(), []int{8}
}

func (x *SearchCheckResponse) GetStatus() SearchCheckResponse_Status {
	if x != nil {
		return x.Status
	}
	return SearchCheckResponse_SUCCESS
}

func (x *SearchCheckResponse) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

func (x *SearchCheckResponse) GetCheck() *CheckInfo {
	if x != nil {
		return x.Check
	}
	return nil
}

type SearchCheckByTeacherIDResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status SearchCheckByTeacherIDResponse_Status `protobuf:"varint,1,opt,name=status,proto3,enum=go.micro.service.check.SearchCheckByTeacherIDResponse_Status" json:"status,omitempty"`
	Msg    string                                `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	Checks []*CheckInfo                          `protobuf:"bytes,3,rep,name=checks,proto3" json:"checks,omitempty"`
}

func (x *SearchCheckByTeacherIDResponse) Reset() {
	*x = SearchCheckByTeacherIDResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_check_check_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SearchCheckByTeacherIDResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchCheckByTeacherIDResponse) ProtoMessage() {}

func (x *SearchCheckByTeacherIDResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_check_check_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchCheckByTeacherIDResponse.ProtoReflect.Descriptor instead.
func (*SearchCheckByTeacherIDResponse) Descriptor() ([]byte, []int) {
	return file_proto_check_check_proto_rawDescGZIP(), []int{9}
}

func (x *SearchCheckByTeacherIDResponse) GetStatus() SearchCheckByTeacherIDResponse_Status {
	if x != nil {
		return x.Status
	}
	return SearchCheckByTeacherIDResponse_SUCCESS
}

func (x *SearchCheckByTeacherIDResponse) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

func (x *SearchCheckByTeacherIDResponse) GetChecks() []*CheckInfo {
	if x != nil {
		return x.Checks
	}
	return nil
}

type SearchCheckByHomeworkIDResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status SearchCheckByHomeworkIDResponse_Status `protobuf:"varint,1,opt,name=status,proto3,enum=go.micro.service.check.SearchCheckByHomeworkIDResponse_Status" json:"status,omitempty"`
	Msg    string                                 `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	Checks []*CheckInfo                           `protobuf:"bytes,3,rep,name=checks,proto3" json:"checks,omitempty"`
}

func (x *SearchCheckByHomeworkIDResponse) Reset() {
	*x = SearchCheckByHomeworkIDResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_check_check_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SearchCheckByHomeworkIDResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchCheckByHomeworkIDResponse) ProtoMessage() {}

func (x *SearchCheckByHomeworkIDResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_check_check_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchCheckByHomeworkIDResponse.ProtoReflect.Descriptor instead.
func (*SearchCheckByHomeworkIDResponse) Descriptor() ([]byte, []int) {
	return file_proto_check_check_proto_rawDescGZIP(), []int{10}
}

func (x *SearchCheckByHomeworkIDResponse) GetStatus() SearchCheckByHomeworkIDResponse_Status {
	if x != nil {
		return x.Status
	}
	return SearchCheckByHomeworkIDResponse_SUCCESS
}

func (x *SearchCheckByHomeworkIDResponse) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

func (x *SearchCheckByHomeworkIDResponse) GetChecks() []*CheckInfo {
	if x != nil {
		return x.Checks
	}
	return nil
}

var File_proto_check_check_proto protoreflect.FileDescriptor

var file_proto_check_check_proto_rawDesc = []byte{
	0x0a, 0x17, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x63, 0x68, 0x65, 0x63, 0x6b, 0x2f, 0x63, 0x68,
	0x65, 0x63, 0x6b, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x16, 0x67, 0x6f, 0x2e, 0x6d, 0x69,
	0x63, 0x72, 0x6f, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x63, 0x68, 0x65, 0x63,
	0x6b, 0x22, 0xa9, 0x01, 0x0a, 0x10, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x43, 0x68, 0x65, 0x63,
	0x6b, 0x50, 0x61, 0x72, 0x61, 0x6d, 0x12, 0x1a, 0x0a, 0x08, 0x41, 0x6e, 0x73, 0x77, 0x65, 0x72,
	0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x08, 0x41, 0x6e, 0x73, 0x77, 0x65, 0x72,
	0x49, 0x44, 0x12, 0x1e, 0x0a, 0x0a, 0x68, 0x6f, 0x6d, 0x65, 0x77, 0x6f, 0x72, 0x6b, 0x49, 0x44,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0a, 0x68, 0x6f, 0x6d, 0x65, 0x77, 0x6f, 0x72, 0x6b,
	0x49, 0x44, 0x12, 0x1c, 0x0a, 0x09, 0x74, 0x65, 0x61, 0x63, 0x68, 0x65, 0x72, 0x49, 0x44, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x09, 0x74, 0x65, 0x61, 0x63, 0x68, 0x65, 0x72, 0x49, 0x44,
	0x12, 0x1c, 0x0a, 0x09, 0x63, 0x68, 0x65, 0x63, 0x6b, 0x54, 0x69, 0x6d, 0x65, 0x18, 0x04, 0x20,
	0x01, 0x28, 0x03, 0x52, 0x09, 0x63, 0x68, 0x65, 0x63, 0x6b, 0x54, 0x69, 0x6d, 0x65, 0x12, 0x1d,
	0x0a, 0x0a, 0x63, 0x68, 0x65, 0x63, 0x6b, 0x5f, 0x6a, 0x73, 0x6f, 0x6e, 0x18, 0x05, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x09, 0x63, 0x68, 0x65, 0x63, 0x6b, 0x4a, 0x73, 0x6f, 0x6e, 0x22, 0x23, 0x0a,
	0x07, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x49, 0x44, 0x12, 0x18, 0x0a, 0x07, 0x43, 0x68, 0x65, 0x63,
	0x6b, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x07, 0x43, 0x68, 0x65, 0x63, 0x6b,
	0x49, 0x44, 0x22, 0xbc, 0x01, 0x0a, 0x09, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x49, 0x6e, 0x66, 0x6f,
	0x12, 0x18, 0x0a, 0x07, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x07, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x49, 0x44, 0x12, 0x1a, 0x0a, 0x08, 0x41, 0x6e,
	0x73, 0x77, 0x65, 0x72, 0x49, 0x44, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x08, 0x41, 0x6e,
	0x73, 0x77, 0x65, 0x72, 0x49, 0x44, 0x12, 0x1e, 0x0a, 0x0a, 0x68, 0x6f, 0x6d, 0x65, 0x77, 0x6f,
	0x72, 0x6b, 0x49, 0x44, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0a, 0x68, 0x6f, 0x6d, 0x65,
	0x77, 0x6f, 0x72, 0x6b, 0x49, 0x44, 0x12, 0x1c, 0x0a, 0x09, 0x74, 0x65, 0x61, 0x63, 0x68, 0x65,
	0x72, 0x49, 0x44, 0x18, 0x04, 0x20, 0x01, 0x28, 0x05, 0x52, 0x09, 0x74, 0x65, 0x61, 0x63, 0x68,
	0x65, 0x72, 0x49, 0x44, 0x12, 0x1c, 0x0a, 0x09, 0x63, 0x68, 0x65, 0x63, 0x6b, 0x54, 0x69, 0x6d,
	0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x03, 0x52, 0x09, 0x63, 0x68, 0x65, 0x63, 0x6b, 0x54, 0x69,
	0x6d, 0x65, 0x12, 0x1d, 0x0a, 0x0a, 0x63, 0x68, 0x65, 0x63, 0x6b, 0x5f, 0x6a, 0x73, 0x6f, 0x6e,
	0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x63, 0x68, 0x65, 0x63, 0x6b, 0x4a, 0x73, 0x6f,
	0x6e, 0x22, 0x29, 0x0a, 0x09, 0x54, 0x65, 0x61, 0x63, 0x68, 0x65, 0x72, 0x49, 0x44, 0x12, 0x1c,
	0x0a, 0x09, 0x54, 0x65, 0x61, 0x63, 0x68, 0x65, 0x72, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x09, 0x54, 0x65, 0x61, 0x63, 0x68, 0x65, 0x72, 0x49, 0x44, 0x22, 0x2c, 0x0a, 0x0a,
	0x48, 0x6f, 0x6d, 0x65, 0x77, 0x6f, 0x72, 0x6b, 0x49, 0x44, 0x12, 0x1e, 0x0a, 0x0a, 0x48, 0x6f,
	0x6d, 0x65, 0x77, 0x6f, 0x72, 0x6b, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0a,
	0x48, 0x6f, 0x6d, 0x65, 0x77, 0x6f, 0x72, 0x6b, 0x49, 0x44, 0x22, 0xb8, 0x01, 0x0a, 0x13, 0x43,
	0x72, 0x65, 0x61, 0x74, 0x65, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x12, 0x4a, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0e, 0x32, 0x32, 0x2e, 0x67, 0x6f, 0x2e, 0x6d, 0x69, 0x63, 0x72, 0x6f, 0x2e, 0x73, 0x65,
	0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x63, 0x68, 0x65, 0x63, 0x6b, 0x2e, 0x43, 0x72, 0x65, 0x61,
	0x74, 0x65, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x2e,
	0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x10,
	0x0a, 0x03, 0x6d, 0x73, 0x67, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6d, 0x73, 0x67,
	0x12, 0x18, 0x0a, 0x07, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x49, 0x44, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x07, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x49, 0x44, 0x22, 0x29, 0x0a, 0x06, 0x53, 0x74,
	0x61, 0x74, 0x75, 0x73, 0x12, 0x0b, 0x0a, 0x07, 0x53, 0x55, 0x43, 0x43, 0x45, 0x53, 0x53, 0x10,
	0x00, 0x12, 0x12, 0x0a, 0x05, 0x45, 0x52, 0x52, 0x4f, 0x52, 0x10, 0xff, 0xff, 0xff, 0xff, 0xff,
	0xff, 0xff, 0xff, 0xff, 0x01, 0x22, 0x9e, 0x01, 0x0a, 0x13, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65,
	0x43, 0x68, 0x65, 0x63, 0x6b, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x4a, 0x0a,
	0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x32, 0x2e,
	0x67, 0x6f, 0x2e, 0x6d, 0x69, 0x63, 0x72, 0x6f, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65,
	0x2e, 0x63, 0x68, 0x65, 0x63, 0x6b, 0x2e, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x43, 0x68, 0x65,
	0x63, 0x6b, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x2e, 0x53, 0x74, 0x61, 0x74, 0x75,
	0x73, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x10, 0x0a, 0x03, 0x6d, 0x73, 0x67,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6d, 0x73, 0x67, 0x22, 0x29, 0x0a, 0x06, 0x53,
	0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x0b, 0x0a, 0x07, 0x53, 0x55, 0x43, 0x43, 0x45, 0x53, 0x53,
	0x10, 0x00, 0x12, 0x12, 0x0a, 0x05, 0x45, 0x52, 0x52, 0x4f, 0x52, 0x10, 0xff, 0xff, 0xff, 0xff,
	0xff, 0xff, 0xff, 0xff, 0xff, 0x01, 0x22, 0x9e, 0x01, 0x0a, 0x13, 0x55, 0x70, 0x64, 0x61, 0x74,
	0x65, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x4a,
	0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x32,
	0x2e, 0x67, 0x6f, 0x2e, 0x6d, 0x69, 0x63, 0x72, 0x6f, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63,
	0x65, 0x2e, 0x63, 0x68, 0x65, 0x63, 0x6b, 0x2e, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x43, 0x68,
	0x65, 0x63, 0x6b, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x2e, 0x53, 0x74, 0x61, 0x74,
	0x75, 0x73, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x10, 0x0a, 0x03, 0x6d, 0x73,
	0x67, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6d, 0x73, 0x67, 0x22, 0x29, 0x0a, 0x06,
	0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x0b, 0x0a, 0x07, 0x53, 0x55, 0x43, 0x43, 0x45, 0x53,
	0x53, 0x10, 0x00, 0x12, 0x12, 0x0a, 0x05, 0x45, 0x52, 0x52, 0x4f, 0x52, 0x10, 0xff, 0xff, 0xff,
	0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0x01, 0x22, 0xd7, 0x01, 0x0a, 0x13, 0x53, 0x65, 0x61, 0x72,
	0x63, 0x68, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12,
	0x4a, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32,
	0x32, 0x2e, 0x67, 0x6f, 0x2e, 0x6d, 0x69, 0x63, 0x72, 0x6f, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x69,
	0x63, 0x65, 0x2e, 0x63, 0x68, 0x65, 0x63, 0x6b, 0x2e, 0x53, 0x65, 0x61, 0x72, 0x63, 0x68, 0x43,
	0x68, 0x65, 0x63, 0x6b, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x2e, 0x53, 0x74, 0x61,
	0x74, 0x75, 0x73, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x10, 0x0a, 0x03, 0x6d,
	0x73, 0x67, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6d, 0x73, 0x67, 0x12, 0x37, 0x0a,
	0x05, 0x63, 0x68, 0x65, 0x63, 0x6b, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x21, 0x2e, 0x67,
	0x6f, 0x2e, 0x6d, 0x69, 0x63, 0x72, 0x6f, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e,
	0x63, 0x68, 0x65, 0x63, 0x6b, 0x2e, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x49, 0x6e, 0x66, 0x6f, 0x52,
	0x05, 0x63, 0x68, 0x65, 0x63, 0x6b, 0x22, 0x29, 0x0a, 0x06, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73,
	0x12, 0x0b, 0x0a, 0x07, 0x53, 0x55, 0x43, 0x43, 0x45, 0x53, 0x53, 0x10, 0x00, 0x12, 0x12, 0x0a,
	0x05, 0x45, 0x52, 0x52, 0x4f, 0x52, 0x10, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff,
	0x01, 0x22, 0xef, 0x01, 0x0a, 0x1e, 0x53, 0x65, 0x61, 0x72, 0x63, 0x68, 0x43, 0x68, 0x65, 0x63,
	0x6b, 0x42, 0x79, 0x54, 0x65, 0x61, 0x63, 0x68, 0x65, 0x72, 0x49, 0x44, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x12, 0x55, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0e, 0x32, 0x3d, 0x2e, 0x67, 0x6f, 0x2e, 0x6d, 0x69, 0x63, 0x72, 0x6f, 0x2e,
	0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x63, 0x68, 0x65, 0x63, 0x6b, 0x2e, 0x53, 0x65,
	0x61, 0x72, 0x63, 0x68, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x42, 0x79, 0x54, 0x65, 0x61, 0x63, 0x68,
	0x65, 0x72, 0x49, 0x44, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x2e, 0x53, 0x74, 0x61,
	0x74, 0x75, 0x73, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x10, 0x0a, 0x03, 0x6d,
	0x73, 0x67, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6d, 0x73, 0x67, 0x12, 0x39, 0x0a,
	0x06, 0x63, 0x68, 0x65, 0x63, 0x6b, 0x73, 0x18, 0x03, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x21, 0x2e,
	0x67, 0x6f, 0x2e, 0x6d, 0x69, 0x63, 0x72, 0x6f, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65,
	0x2e, 0x63, 0x68, 0x65, 0x63, 0x6b, 0x2e, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x49, 0x6e, 0x66, 0x6f,
	0x52, 0x06, 0x63, 0x68, 0x65, 0x63, 0x6b, 0x73, 0x22, 0x29, 0x0a, 0x06, 0x53, 0x74, 0x61, 0x74,
	0x75, 0x73, 0x12, 0x0b, 0x0a, 0x07, 0x53, 0x55, 0x43, 0x43, 0x45, 0x53, 0x53, 0x10, 0x00, 0x12,
	0x12, 0x0a, 0x05, 0x45, 0x52, 0x52, 0x4f, 0x52, 0x10, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff,
	0xff, 0xff, 0x01, 0x22, 0xf1, 0x01, 0x0a, 0x1f, 0x53, 0x65, 0x61, 0x72, 0x63, 0x68, 0x43, 0x68,
	0x65, 0x63, 0x6b, 0x42, 0x79, 0x48, 0x6f, 0x6d, 0x65, 0x77, 0x6f, 0x72, 0x6b, 0x49, 0x44, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x56, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75,
	0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x3e, 0x2e, 0x67, 0x6f, 0x2e, 0x6d, 0x69, 0x63,
	0x72, 0x6f, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x63, 0x68, 0x65, 0x63, 0x6b,
	0x2e, 0x53, 0x65, 0x61, 0x72, 0x63, 0x68, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x42, 0x79, 0x48, 0x6f,
	0x6d, 0x65, 0x77, 0x6f, 0x72, 0x6b, 0x49, 0x44, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x2e, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12,
	0x10, 0x0a, 0x03, 0x6d, 0x73, 0x67, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6d, 0x73,
	0x67, 0x12, 0x39, 0x0a, 0x06, 0x63, 0x68, 0x65, 0x63, 0x6b, 0x73, 0x18, 0x03, 0x20, 0x03, 0x28,
	0x0b, 0x32, 0x21, 0x2e, 0x67, 0x6f, 0x2e, 0x6d, 0x69, 0x63, 0x72, 0x6f, 0x2e, 0x73, 0x65, 0x72,
	0x76, 0x69, 0x63, 0x65, 0x2e, 0x63, 0x68, 0x65, 0x63, 0x6b, 0x2e, 0x43, 0x68, 0x65, 0x63, 0x6b,
	0x49, 0x6e, 0x66, 0x6f, 0x52, 0x06, 0x63, 0x68, 0x65, 0x63, 0x6b, 0x73, 0x22, 0x29, 0x0a, 0x06,
	0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x0b, 0x0a, 0x07, 0x53, 0x55, 0x43, 0x43, 0x45, 0x53,
	0x53, 0x10, 0x00, 0x12, 0x12, 0x0a, 0x05, 0x45, 0x52, 0x52, 0x4f, 0x52, 0x10, 0xff, 0xff, 0xff,
	0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0x01, 0x32, 0x86, 0x05, 0x0a, 0x0c, 0x43, 0x68, 0x65, 0x63,
	0x6b, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x66, 0x0a, 0x0b, 0x43, 0x72, 0x65, 0x61,
	0x74, 0x65, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x12, 0x28, 0x2e, 0x67, 0x6f, 0x2e, 0x6d, 0x69, 0x63,
	0x72, 0x6f, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x63, 0x68, 0x65, 0x63, 0x6b,
	0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x50, 0x61, 0x72, 0x61,
	0x6d, 0x1a, 0x2b, 0x2e, 0x67, 0x6f, 0x2e, 0x6d, 0x69, 0x63, 0x72, 0x6f, 0x2e, 0x73, 0x65, 0x72,
	0x76, 0x69, 0x63, 0x65, 0x2e, 0x63, 0x68, 0x65, 0x63, 0x6b, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74,
	0x65, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00,
	0x12, 0x5d, 0x0a, 0x0b, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x12,
	0x1f, 0x2e, 0x67, 0x6f, 0x2e, 0x6d, 0x69, 0x63, 0x72, 0x6f, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x69,
	0x63, 0x65, 0x2e, 0x63, 0x68, 0x65, 0x63, 0x6b, 0x2e, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x49, 0x44,
	0x1a, 0x2b, 0x2e, 0x67, 0x6f, 0x2e, 0x6d, 0x69, 0x63, 0x72, 0x6f, 0x2e, 0x73, 0x65, 0x72, 0x76,
	0x69, 0x63, 0x65, 0x2e, 0x63, 0x68, 0x65, 0x63, 0x6b, 0x2e, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65,
	0x43, 0x68, 0x65, 0x63, 0x6b, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12,
	0x5f, 0x0a, 0x0b, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x12, 0x21,
	0x2e, 0x67, 0x6f, 0x2e, 0x6d, 0x69, 0x63, 0x72, 0x6f, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63,
	0x65, 0x2e, 0x63, 0x68, 0x65, 0x63, 0x6b, 0x2e, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x49, 0x6e, 0x66,
	0x6f, 0x1a, 0x2b, 0x2e, 0x67, 0x6f, 0x2e, 0x6d, 0x69, 0x63, 0x72, 0x6f, 0x2e, 0x73, 0x65, 0x72,
	0x76, 0x69, 0x63, 0x65, 0x2e, 0x63, 0x68, 0x65, 0x63, 0x6b, 0x2e, 0x55, 0x70, 0x64, 0x61, 0x74,
	0x65, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00,
	0x12, 0x5d, 0x0a, 0x0b, 0x53, 0x65, 0x61, 0x72, 0x63, 0x68, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x12,
	0x1f, 0x2e, 0x67, 0x6f, 0x2e, 0x6d, 0x69, 0x63, 0x72, 0x6f, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x69,
	0x63, 0x65, 0x2e, 0x63, 0x68, 0x65, 0x63, 0x6b, 0x2e, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x49, 0x44,
	0x1a, 0x2b, 0x2e, 0x67, 0x6f, 0x2e, 0x6d, 0x69, 0x63, 0x72, 0x6f, 0x2e, 0x73, 0x65, 0x72, 0x76,
	0x69, 0x63, 0x65, 0x2e, 0x63, 0x68, 0x65, 0x63, 0x6b, 0x2e, 0x53, 0x65, 0x61, 0x72, 0x63, 0x68,
	0x43, 0x68, 0x65, 0x63, 0x6b, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12,
	0x75, 0x0a, 0x16, 0x53, 0x65, 0x61, 0x72, 0x63, 0x68, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x42, 0x79,
	0x54, 0x65, 0x61, 0x63, 0x68, 0x65, 0x72, 0x49, 0x44, 0x12, 0x21, 0x2e, 0x67, 0x6f, 0x2e, 0x6d,
	0x69, 0x63, 0x72, 0x6f, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x63, 0x68, 0x65,
	0x63, 0x6b, 0x2e, 0x54, 0x65, 0x61, 0x63, 0x68, 0x65, 0x72, 0x49, 0x44, 0x1a, 0x36, 0x2e, 0x67,
	0x6f, 0x2e, 0x6d, 0x69, 0x63, 0x72, 0x6f, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e,
	0x63, 0x68, 0x65, 0x63, 0x6b, 0x2e, 0x53, 0x65, 0x61, 0x72, 0x63, 0x68, 0x43, 0x68, 0x65, 0x63,
	0x6b, 0x42, 0x79, 0x54, 0x65, 0x61, 0x63, 0x68, 0x65, 0x72, 0x49, 0x44, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x78, 0x0a, 0x17, 0x53, 0x65, 0x61, 0x72, 0x63, 0x68,
	0x43, 0x68, 0x65, 0x63, 0x6b, 0x42, 0x79, 0x48, 0x6f, 0x6d, 0x65, 0x77, 0x6f, 0x72, 0x6b, 0x49,
	0x44, 0x12, 0x22, 0x2e, 0x67, 0x6f, 0x2e, 0x6d, 0x69, 0x63, 0x72, 0x6f, 0x2e, 0x73, 0x65, 0x72,
	0x76, 0x69, 0x63, 0x65, 0x2e, 0x63, 0x68, 0x65, 0x63, 0x6b, 0x2e, 0x48, 0x6f, 0x6d, 0x65, 0x77,
	0x6f, 0x72, 0x6b, 0x49, 0x44, 0x1a, 0x37, 0x2e, 0x67, 0x6f, 0x2e, 0x6d, 0x69, 0x63, 0x72, 0x6f,
	0x2e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x63, 0x68, 0x65, 0x63, 0x6b, 0x2e, 0x53,
	0x65, 0x61, 0x72, 0x63, 0x68, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x42, 0x79, 0x48, 0x6f, 0x6d, 0x65,
	0x77, 0x6f, 0x72, 0x6b, 0x49, 0x44, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00,
	0x42, 0x0d, 0x5a, 0x0b, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x63, 0x68, 0x65, 0x63, 0x6b, 0x62,
	0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_proto_check_check_proto_rawDescOnce sync.Once
	file_proto_check_check_proto_rawDescData = file_proto_check_check_proto_rawDesc
)

func file_proto_check_check_proto_rawDescGZIP() []byte {
	file_proto_check_check_proto_rawDescOnce.Do(func() {
		file_proto_check_check_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_check_check_proto_rawDescData)
	})
	return file_proto_check_check_proto_rawDescData
}

var file_proto_check_check_proto_enumTypes = make([]protoimpl.EnumInfo, 6)
var file_proto_check_check_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_proto_check_check_proto_goTypes = []interface{}{
	(CreateCheckResponse_Status)(0),             // 0: go.micro.service.check.CreateCheckResponse.Status
	(DeleteCheckResponse_Status)(0),             // 1: go.micro.service.check.DeleteCheckResponse.Status
	(UpdateCheckResponse_Status)(0),             // 2: go.micro.service.check.UpdateCheckResponse.Status
	(SearchCheckResponse_Status)(0),             // 3: go.micro.service.check.SearchCheckResponse.Status
	(SearchCheckByTeacherIDResponse_Status)(0),  // 4: go.micro.service.check.SearchCheckByTeacherIDResponse.Status
	(SearchCheckByHomeworkIDResponse_Status)(0), // 5: go.micro.service.check.SearchCheckByHomeworkIDResponse.Status
	(*CreateCheckParam)(nil),                    // 6: go.micro.service.check.CreateCheckParam
	(*CheckID)(nil),                             // 7: go.micro.service.check.CheckID
	(*CheckInfo)(nil),                           // 8: go.micro.service.check.CheckInfo
	(*TeacherID)(nil),                           // 9: go.micro.service.check.TeacherID
	(*HomeworkID)(nil),                          // 10: go.micro.service.check.HomeworkID
	(*CreateCheckResponse)(nil),                 // 11: go.micro.service.check.CreateCheckResponse
	(*DeleteCheckResponse)(nil),                 // 12: go.micro.service.check.DeleteCheckResponse
	(*UpdateCheckResponse)(nil),                 // 13: go.micro.service.check.UpdateCheckResponse
	(*SearchCheckResponse)(nil),                 // 14: go.micro.service.check.SearchCheckResponse
	(*SearchCheckByTeacherIDResponse)(nil),      // 15: go.micro.service.check.SearchCheckByTeacherIDResponse
	(*SearchCheckByHomeworkIDResponse)(nil),     // 16: go.micro.service.check.SearchCheckByHomeworkIDResponse
}
var file_proto_check_check_proto_depIdxs = []int32{
	0,  // 0: go.micro.service.check.CreateCheckResponse.status:type_name -> go.micro.service.check.CreateCheckResponse.Status
	1,  // 1: go.micro.service.check.DeleteCheckResponse.status:type_name -> go.micro.service.check.DeleteCheckResponse.Status
	2,  // 2: go.micro.service.check.UpdateCheckResponse.status:type_name -> go.micro.service.check.UpdateCheckResponse.Status
	3,  // 3: go.micro.service.check.SearchCheckResponse.status:type_name -> go.micro.service.check.SearchCheckResponse.Status
	8,  // 4: go.micro.service.check.SearchCheckResponse.check:type_name -> go.micro.service.check.CheckInfo
	4,  // 5: go.micro.service.check.SearchCheckByTeacherIDResponse.status:type_name -> go.micro.service.check.SearchCheckByTeacherIDResponse.Status
	8,  // 6: go.micro.service.check.SearchCheckByTeacherIDResponse.checks:type_name -> go.micro.service.check.CheckInfo
	5,  // 7: go.micro.service.check.SearchCheckByHomeworkIDResponse.status:type_name -> go.micro.service.check.SearchCheckByHomeworkIDResponse.Status
	8,  // 8: go.micro.service.check.SearchCheckByHomeworkIDResponse.checks:type_name -> go.micro.service.check.CheckInfo
	6,  // 9: go.micro.service.check.CheckService.CreateCheck:input_type -> go.micro.service.check.CreateCheckParam
	7,  // 10: go.micro.service.check.CheckService.DeleteCheck:input_type -> go.micro.service.check.CheckID
	8,  // 11: go.micro.service.check.CheckService.UpdateCheck:input_type -> go.micro.service.check.CheckInfo
	7,  // 12: go.micro.service.check.CheckService.SearchCheck:input_type -> go.micro.service.check.CheckID
	9,  // 13: go.micro.service.check.CheckService.SearchCheckByTeacherID:input_type -> go.micro.service.check.TeacherID
	10, // 14: go.micro.service.check.CheckService.SearchCheckByHomeworkID:input_type -> go.micro.service.check.HomeworkID
	11, // 15: go.micro.service.check.CheckService.CreateCheck:output_type -> go.micro.service.check.CreateCheckResponse
	12, // 16: go.micro.service.check.CheckService.DeleteCheck:output_type -> go.micro.service.check.DeleteCheckResponse
	13, // 17: go.micro.service.check.CheckService.UpdateCheck:output_type -> go.micro.service.check.UpdateCheckResponse
	14, // 18: go.micro.service.check.CheckService.SearchCheck:output_type -> go.micro.service.check.SearchCheckResponse
	15, // 19: go.micro.service.check.CheckService.SearchCheckByTeacherID:output_type -> go.micro.service.check.SearchCheckByTeacherIDResponse
	16, // 20: go.micro.service.check.CheckService.SearchCheckByHomeworkID:output_type -> go.micro.service.check.SearchCheckByHomeworkIDResponse
	15, // [15:21] is the sub-list for method output_type
	9,  // [9:15] is the sub-list for method input_type
	9,  // [9:9] is the sub-list for extension type_name
	9,  // [9:9] is the sub-list for extension extendee
	0,  // [0:9] is the sub-list for field type_name
}

func init() { file_proto_check_check_proto_init() }
func file_proto_check_check_proto_init() {
	if File_proto_check_check_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_proto_check_check_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateCheckParam); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_check_check_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CheckID); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_check_check_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CheckInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_check_check_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TeacherID); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_check_check_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*HomeworkID); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_check_check_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateCheckResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_check_check_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteCheckResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_check_check_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateCheckResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_check_check_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SearchCheckResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_check_check_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SearchCheckByTeacherIDResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_check_check_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SearchCheckByHomeworkIDResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_check_check_proto_rawDesc,
			NumEnums:      6,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_check_check_proto_goTypes,
		DependencyIndexes: file_proto_check_check_proto_depIdxs,
		EnumInfos:         file_proto_check_check_proto_enumTypes,
		MessageInfos:      file_proto_check_check_proto_msgTypes,
	}.Build()
	File_proto_check_check_proto = out.File
	file_proto_check_check_proto_rawDesc = nil
	file_proto_check_check_proto_goTypes = nil
	file_proto_check_check_proto_depIdxs = nil
}
