//声明proto本版

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0
// 	protoc        v3.14.0
// source: proto/verification/verification.proto

//服务名

package verification

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type SendCodeEmailResponse_Status int32

const (
	SendCodeEmailResponse_SUCCESS SendCodeEmailResponse_Status = 0
	SendCodeEmailResponse_ERROR   SendCodeEmailResponse_Status = -1
)

// Enum value maps for SendCodeEmailResponse_Status.
var (
	SendCodeEmailResponse_Status_name = map[int32]string{
		0:  "SUCCESS",
		-1: "ERROR",
	}
	SendCodeEmailResponse_Status_value = map[string]int32{
		"SUCCESS": 0,
		"ERROR":   -1,
	}
)

func (x SendCodeEmailResponse_Status) Enum() *SendCodeEmailResponse_Status {
	p := new(SendCodeEmailResponse_Status)
	*p = x
	return p
}

func (x SendCodeEmailResponse_Status) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SendCodeEmailResponse_Status) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_verification_verification_proto_enumTypes[0].Descriptor()
}

func (SendCodeEmailResponse_Status) Type() protoreflect.EnumType {
	return &file_proto_verification_verification_proto_enumTypes[0]
}

func (x SendCodeEmailResponse_Status) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SendCodeEmailResponse_Status.Descriptor instead.
func (SendCodeEmailResponse_Status) EnumDescriptor() ([]byte, []int) {
	return file_proto_verification_verification_proto_rawDescGZIP(), []int{1, 0}
}

type VerifyCodeEmailResponse_Status int32

const (
	VerifyCodeEmailResponse_SUCCESS VerifyCodeEmailResponse_Status = 0
	VerifyCodeEmailResponse_ERROR   VerifyCodeEmailResponse_Status = -1
)

// Enum value maps for VerifyCodeEmailResponse_Status.
var (
	VerifyCodeEmailResponse_Status_name = map[int32]string{
		0:  "SUCCESS",
		-1: "ERROR",
	}
	VerifyCodeEmailResponse_Status_value = map[string]int32{
		"SUCCESS": 0,
		"ERROR":   -1,
	}
)

func (x VerifyCodeEmailResponse_Status) Enum() *VerifyCodeEmailResponse_Status {
	p := new(VerifyCodeEmailResponse_Status)
	*p = x
	return p
}

func (x VerifyCodeEmailResponse_Status) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (VerifyCodeEmailResponse_Status) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_verification_verification_proto_enumTypes[1].Descriptor()
}

func (VerifyCodeEmailResponse_Status) Type() protoreflect.EnumType {
	return &file_proto_verification_verification_proto_enumTypes[1]
}

func (x VerifyCodeEmailResponse_Status) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use VerifyCodeEmailResponse_Status.Descriptor instead.
func (VerifyCodeEmailResponse_Status) EnumDescriptor() ([]byte, []int) {
	return file_proto_verification_verification_proto_rawDescGZIP(), []int{3, 0}
}

type SendCodeEmailParam struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Email    string `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	Username string `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
}

func (x *SendCodeEmailParam) Reset() {
	*x = SendCodeEmailParam{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_verification_verification_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SendCodeEmailParam) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendCodeEmailParam) ProtoMessage() {}

func (x *SendCodeEmailParam) ProtoReflect() protoreflect.Message {
	mi := &file_proto_verification_verification_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendCodeEmailParam.ProtoReflect.Descriptor instead.
func (*SendCodeEmailParam) Descriptor() ([]byte, []int) {
	return file_proto_verification_verification_proto_rawDescGZIP(), []int{0}
}

func (x *SendCodeEmailParam) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *SendCodeEmailParam) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

type SendCodeEmailResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status  SendCodeEmailResponse_Status `protobuf:"varint,1,opt,name=status,proto3,enum=go.micro.service.verification.SendCodeEmailResponse_Status" json:"status,omitempty"`
	Message string                       `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
}

func (x *SendCodeEmailResponse) Reset() {
	*x = SendCodeEmailResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_verification_verification_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SendCodeEmailResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendCodeEmailResponse) ProtoMessage() {}

func (x *SendCodeEmailResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_verification_verification_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendCodeEmailResponse.ProtoReflect.Descriptor instead.
func (*SendCodeEmailResponse) Descriptor() ([]byte, []int) {
	return file_proto_verification_verification_proto_rawDescGZIP(), []int{1}
}

func (x *SendCodeEmailResponse) GetStatus() SendCodeEmailResponse_Status {
	if x != nil {
		return x.Status
	}
	return SendCodeEmailResponse_SUCCESS
}

func (x *SendCodeEmailResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type VerifyCodeEmailParam struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Email    string `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	Username string `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	Code     string `protobuf:"bytes,3,opt,name=code,proto3" json:"code,omitempty"`
}

func (x *VerifyCodeEmailParam) Reset() {
	*x = VerifyCodeEmailParam{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_verification_verification_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *VerifyCodeEmailParam) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VerifyCodeEmailParam) ProtoMessage() {}

func (x *VerifyCodeEmailParam) ProtoReflect() protoreflect.Message {
	mi := &file_proto_verification_verification_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VerifyCodeEmailParam.ProtoReflect.Descriptor instead.
func (*VerifyCodeEmailParam) Descriptor() ([]byte, []int) {
	return file_proto_verification_verification_proto_rawDescGZIP(), []int{2}
}

func (x *VerifyCodeEmailParam) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *VerifyCodeEmailParam) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *VerifyCodeEmailParam) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

type VerifyCodeEmailResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status  VerifyCodeEmailResponse_Status `protobuf:"varint,1,opt,name=status,proto3,enum=go.micro.service.verification.VerifyCodeEmailResponse_Status" json:"status,omitempty"`
	Message string                         `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
}

func (x *VerifyCodeEmailResponse) Reset() {
	*x = VerifyCodeEmailResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_verification_verification_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *VerifyCodeEmailResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VerifyCodeEmailResponse) ProtoMessage() {}

func (x *VerifyCodeEmailResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_verification_verification_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VerifyCodeEmailResponse.ProtoReflect.Descriptor instead.
func (*VerifyCodeEmailResponse) Descriptor() ([]byte, []int) {
	return file_proto_verification_verification_proto_rawDescGZIP(), []int{3}
}

func (x *VerifyCodeEmailResponse) GetStatus() VerifyCodeEmailResponse_Status {
	if x != nil {
		return x.Status
	}
	return VerifyCodeEmailResponse_SUCCESS
}

func (x *VerifyCodeEmailResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_proto_verification_verification_proto protoreflect.FileDescriptor

var file_proto_verification_verification_proto_rawDesc = []byte{
	0x0a, 0x25, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x76, 0x65, 0x72, 0x69, 0x66, 0x69, 0x63, 0x61,
	0x74, 0x69, 0x6f, 0x6e, 0x2f, 0x76, 0x65, 0x72, 0x69, 0x66, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f,
	0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x1d, 0x67, 0x6f, 0x2e, 0x6d, 0x69, 0x63, 0x72,
	0x6f, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x76, 0x65, 0x72, 0x69, 0x66, 0x69,
	0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x22, 0x46, 0x0a, 0x12, 0x53, 0x65, 0x6e, 0x64, 0x43, 0x6f,
	0x64, 0x65, 0x45, 0x6d, 0x61, 0x69, 0x6c, 0x50, 0x61, 0x72, 0x61, 0x6d, 0x12, 0x14, 0x0a, 0x05,
	0x65, 0x6d, 0x61, 0x69, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x65, 0x6d, 0x61,
	0x69, 0x6c, 0x12, 0x1a, 0x0a, 0x08, 0x75, 0x73, 0x65, 0x72, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x75, 0x73, 0x65, 0x72, 0x6e, 0x61, 0x6d, 0x65, 0x22, 0xb1,
	0x01, 0x0a, 0x15, 0x53, 0x65, 0x6e, 0x64, 0x43, 0x6f, 0x64, 0x65, 0x45, 0x6d, 0x61, 0x69, 0x6c,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x53, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74,
	0x75, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x3b, 0x2e, 0x67, 0x6f, 0x2e, 0x6d, 0x69,
	0x63, 0x72, 0x6f, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x76, 0x65, 0x72, 0x69,
	0x66, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x53, 0x65, 0x6e, 0x64, 0x43, 0x6f, 0x64,
	0x65, 0x45, 0x6d, 0x61, 0x69, 0x6c, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x2e, 0x53,
	0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x18, 0x0a,
	0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07,
	0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x22, 0x29, 0x0a, 0x06, 0x53, 0x74, 0x61, 0x74, 0x75,
	0x73, 0x12, 0x0b, 0x0a, 0x07, 0x53, 0x55, 0x43, 0x43, 0x45, 0x53, 0x53, 0x10, 0x00, 0x12, 0x12,
	0x0a, 0x05, 0x45, 0x52, 0x52, 0x4f, 0x52, 0x10, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff,
	0xff, 0x01, 0x22, 0x5c, 0x0a, 0x14, 0x56, 0x65, 0x72, 0x69, 0x66, 0x79, 0x43, 0x6f, 0x64, 0x65,
	0x45, 0x6d, 0x61, 0x69, 0x6c, 0x50, 0x61, 0x72, 0x61, 0x6d, 0x12, 0x14, 0x0a, 0x05, 0x65, 0x6d,
	0x61, 0x69, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x65, 0x6d, 0x61, 0x69, 0x6c,
	0x12, 0x1a, 0x0a, 0x08, 0x75, 0x73, 0x65, 0x72, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x08, 0x75, 0x73, 0x65, 0x72, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x12, 0x0a, 0x04,
	0x63, 0x6f, 0x64, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x63, 0x6f, 0x64, 0x65,
	0x22, 0xb5, 0x01, 0x0a, 0x17, 0x56, 0x65, 0x72, 0x69, 0x66, 0x79, 0x43, 0x6f, 0x64, 0x65, 0x45,
	0x6d, 0x61, 0x69, 0x6c, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x55, 0x0a, 0x06,
	0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x3d, 0x2e, 0x67,
	0x6f, 0x2e, 0x6d, 0x69, 0x63, 0x72, 0x6f, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e,
	0x76, 0x65, 0x72, 0x69, 0x66, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x56, 0x65, 0x72,
	0x69, 0x66, 0x79, 0x43, 0x6f, 0x64, 0x65, 0x45, 0x6d, 0x61, 0x69, 0x6c, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x2e, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x06, 0x73, 0x74, 0x61,
	0x74, 0x75, 0x73, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x22, 0x29, 0x0a,
	0x06, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x0b, 0x0a, 0x07, 0x53, 0x55, 0x43, 0x43, 0x45,
	0x53, 0x53, 0x10, 0x00, 0x12, 0x12, 0x0a, 0x05, 0x45, 0x52, 0x52, 0x4f, 0x52, 0x10, 0xff, 0xff,
	0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0x01, 0x32, 0x94, 0x02, 0x0a, 0x13, 0x56, 0x65, 0x72,
	0x69, 0x66, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65,
	0x12, 0x7a, 0x0a, 0x0d, 0x53, 0x65, 0x6e, 0x64, 0x43, 0x6f, 0x64, 0x65, 0x45, 0x6d, 0x61, 0x69,
	0x6c, 0x12, 0x31, 0x2e, 0x67, 0x6f, 0x2e, 0x6d, 0x69, 0x63, 0x72, 0x6f, 0x2e, 0x73, 0x65, 0x72,
	0x76, 0x69, 0x63, 0x65, 0x2e, 0x76, 0x65, 0x72, 0x69, 0x66, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f,
	0x6e, 0x2e, 0x53, 0x65, 0x6e, 0x64, 0x43, 0x6f, 0x64, 0x65, 0x45, 0x6d, 0x61, 0x69, 0x6c, 0x50,
	0x61, 0x72, 0x61, 0x6d, 0x1a, 0x34, 0x2e, 0x67, 0x6f, 0x2e, 0x6d, 0x69, 0x63, 0x72, 0x6f, 0x2e,
	0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x76, 0x65, 0x72, 0x69, 0x66, 0x69, 0x63, 0x61,
	0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x53, 0x65, 0x6e, 0x64, 0x43, 0x6f, 0x64, 0x65, 0x45, 0x6d, 0x61,
	0x69, 0x6c, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x80, 0x01, 0x0a,
	0x0f, 0x56, 0x65, 0x72, 0x69, 0x66, 0x79, 0x43, 0x6f, 0x64, 0x65, 0x45, 0x6d, 0x61, 0x69, 0x6c,
	0x12, 0x33, 0x2e, 0x67, 0x6f, 0x2e, 0x6d, 0x69, 0x63, 0x72, 0x6f, 0x2e, 0x73, 0x65, 0x72, 0x76,
	0x69, 0x63, 0x65, 0x2e, 0x76, 0x65, 0x72, 0x69, 0x66, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e,
	0x2e, 0x56, 0x65, 0x72, 0x69, 0x66, 0x79, 0x43, 0x6f, 0x64, 0x65, 0x45, 0x6d, 0x61, 0x69, 0x6c,
	0x50, 0x61, 0x72, 0x61, 0x6d, 0x1a, 0x36, 0x2e, 0x67, 0x6f, 0x2e, 0x6d, 0x69, 0x63, 0x72, 0x6f,
	0x2e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x76, 0x65, 0x72, 0x69, 0x66, 0x69, 0x63,
	0x61, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x56, 0x65, 0x72, 0x69, 0x66, 0x79, 0x43, 0x6f, 0x64, 0x65,
	0x45, 0x6d, 0x61, 0x69, 0x6c, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x42,
	0x14, 0x5a, 0x12, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x76, 0x65, 0x72, 0x69, 0x66, 0x69, 0x63,
	0x61, 0x74, 0x69, 0x6f, 0x6e, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_proto_verification_verification_proto_rawDescOnce sync.Once
	file_proto_verification_verification_proto_rawDescData = file_proto_verification_verification_proto_rawDesc
)

func file_proto_verification_verification_proto_rawDescGZIP() []byte {
	file_proto_verification_verification_proto_rawDescOnce.Do(func() {
		file_proto_verification_verification_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_verification_verification_proto_rawDescData)
	})
	return file_proto_verification_verification_proto_rawDescData
}

var file_proto_verification_verification_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_proto_verification_verification_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_proto_verification_verification_proto_goTypes = []interface{}{
	(SendCodeEmailResponse_Status)(0),   // 0: go.micro.service.verification.SendCodeEmailResponse.Status
	(VerifyCodeEmailResponse_Status)(0), // 1: go.micro.service.verification.VerifyCodeEmailResponse.Status
	(*SendCodeEmailParam)(nil),          // 2: go.micro.service.verification.SendCodeEmailParam
	(*SendCodeEmailResponse)(nil),       // 3: go.micro.service.verification.SendCodeEmailResponse
	(*VerifyCodeEmailParam)(nil),        // 4: go.micro.service.verification.VerifyCodeEmailParam
	(*VerifyCodeEmailResponse)(nil),     // 5: go.micro.service.verification.VerifyCodeEmailResponse
}
var file_proto_verification_verification_proto_depIdxs = []int32{
	0, // 0: go.micro.service.verification.SendCodeEmailResponse.status:type_name -> go.micro.service.verification.SendCodeEmailResponse.Status
	1, // 1: go.micro.service.verification.VerifyCodeEmailResponse.status:type_name -> go.micro.service.verification.VerifyCodeEmailResponse.Status
	2, // 2: go.micro.service.verification.VerificationService.SendCodeEmail:input_type -> go.micro.service.verification.SendCodeEmailParam
	4, // 3: go.micro.service.verification.VerificationService.VerifyCodeEmail:input_type -> go.micro.service.verification.VerifyCodeEmailParam
	3, // 4: go.micro.service.verification.VerificationService.SendCodeEmail:output_type -> go.micro.service.verification.SendCodeEmailResponse
	5, // 5: go.micro.service.verification.VerificationService.VerifyCodeEmail:output_type -> go.micro.service.verification.VerifyCodeEmailResponse
	4, // [4:6] is the sub-list for method output_type
	2, // [2:4] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_proto_verification_verification_proto_init() }
func file_proto_verification_verification_proto_init() {
	if File_proto_verification_verification_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_proto_verification_verification_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SendCodeEmailParam); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_verification_verification_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SendCodeEmailResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_verification_verification_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*VerifyCodeEmailParam); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_verification_verification_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*VerifyCodeEmailResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_verification_verification_proto_rawDesc,
			NumEnums:      2,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_verification_verification_proto_goTypes,
		DependencyIndexes: file_proto_verification_verification_proto_depIdxs,
		EnumInfos:         file_proto_verification_verification_proto_enumTypes,
		MessageInfos:      file_proto_verification_verification_proto_msgTypes,
	}.Build()
	File_proto_verification_verification_proto = out.File
	file_proto_verification_verification_proto_rawDesc = nil
	file_proto_verification_verification_proto_goTypes = nil
	file_proto_verification_verification_proto_depIdxs = nil
}
